import { MemoryOwnerStore, NotificationRow } from './owner-store';
const network='signet', at=new Date().toISOString();
const notification:NotificationRow={notification_id:'n1',owner_id:'o1',network,watchlist_id:'w1',rule_id:'r1',event_id:'e1',title:'t',message:'m',severity:'info',entity_type:'txid',blinded_hash:'a'.repeat(64),block_height:1,block_hash:'b'.repeat(64),state:'open',created_at:at,acknowledged_at:null};
async function fixture(){const store=new MemoryOwnerStore();await store.insertRule({rule_id:'r1',owner_id:'o1',network,watchlist_id:'w1',condition_type:'confirmation',threshold_value:null,delivery_channel:'webhook',webhook_id:'h1',enabled:true,rate_limit_per_hour:1,created_at:at,version:1});await store.insertWebhook({webhook_id:'h1',owner_id:'o1',network,url:'https://example.org/',secret_ciphertext:'test',key_version:1,event_filters:[],active:true,created_at:at,updated_at:at});return store;}
describe('durable intent semantics and lease fencing',()=>{
 it('reconciles legacy duplicate notification even when hourly quota is exhausted',async()=>{const store=await fixture();await store.insertNotification(notification);expect(await store.recordNotificationWithDelivery({...notification,notification_id:'replacement'},'h1',1)).toBe('duplicate');const rows=await store.claimOutbox(network,at,new Date(Date.parse(at)+30000).toISOString(),1);expect(rows).toHaveLength(1);expect(rows[0].notification_id).toBe('n1');expect(await store.listNotifications('o1',network,null,10)).toHaveLength(1);});
 it('foreign target cannot commit notification or intent',async()=>{const store=await fixture();await store.insertWebhook({webhook_id:'h1',owner_id:'other',network,url:'https://example.org/',secret_ciphertext:'test',key_version:1,event_filters:[],active:true,created_at:at,updated_at:at});await expect(store.recordNotificationWithDelivery(notification,'h1',1)).rejects.toThrow();expect(await store.listNotifications('o1',network,null,10)).toEqual([]);expect(await store.claimOutbox(network,at,new Date(Date.parse(at)+30000).toISOString(),1)).toEqual([]);});
 it('reclaimed B success cannot be overwritten by late A failure',async()=>{const store=await fixture();await store.recordNotificationWithDelivery(notification,'h1',1);const [a]=await store.claimOutbox(network,at,new Date(Date.parse(at)+10).toISOString(),1);const later=new Date(Date.parse(at)+11).toISOString();const [b]=await store.claimOutbox(network,later,new Date(Date.parse(at)+30000).toISOString(),1);expect(b.attempt_count).toBe(2);expect(b.lease_token).not.toBe(a.lease_token);expect(await store.completeOutbox(b.outbox_id,'delivered',2,later,null,later,b.lease_token!,network)).toBe(true);expect(await store.completeOutbox(a.outbox_id,'pending',1,later,'timeout',later,a.lease_token!,network)).toBe(false);expect(await store.claimOutbox(network,later,new Date(Date.parse(at)+40000).toISOString(),1)).toEqual([]);});
});
