import { randomUUID } from 'crypto';
import { MemoryOwnerStore, useOwnerStore } from './owner-store';
import { queryStudioService } from '../query-studio/query-studio.service';
import config from '../../../config';
const base={owner_id:'owner',network:config.MEMPOOL.NETWORK,created_at:'2026-09-15T00:00:00Z',updated_at:'2026-09-15T00:00:00Z'};
afterEach(()=>useOwnerStore(null));
describe('atomic owner quotas',()=>{
 it('admits only the quota under concurrent requests and preserves existing data',async()=>{const store=new MemoryOwnerStore();const results=await Promise.all(Array.from({length:40},(_,i)=>store.insertSavedQueryWithinQuota({...base,query_id:randomUUID(),title:'Saved'+i,sql_text:'SELECT '+i},5)));expect(results.filter(Boolean)).toHaveLength(5);expect(await store.countSavedQueries(base.owner_id,base.network)).toBe(5);expect(await store.insertSavedQueryWithinQuota({...base,network:'another',query_id:randomUUID(),title:'Separate',sql_text:'SELECT 1'},5)).toBe(true);});
 it('keeps duplicate entity idempotency at the limit and cannot overwrite an existing ID',async()=>{const store=new MemoryOwnerStore();const row={...base,watchlist_id:'list',entity_id:'first',entity_type:'address',blinded_hash:'ab'.repeat(32),label:'original'};expect(await store.insertEntityWithinQuota(row,1)).toBe('inserted');expect(await store.insertEntityWithinQuota({...row,entity_id:'new'},1)).toBe('duplicate');expect(await store.insertEntityWithinQuota({...row,entity_id:'second',blinded_hash:'cd'.repeat(32)},1)).toBe('quota');expect((await store.listEntities('list'))[0]).toEqual(row);});
 it('bounds concurrent watchlist and rule creation',async()=>{const store=new MemoryOwnerStore();const lists=await Promise.all(Array.from({length:20},()=>store.insertWatchlistWithinQuota({...base,watchlist_id:randomUUID(),name:'Watch',privacy_mode:'blinded',version:1},3)));expect(lists.filter(Boolean)).toHaveLength(3);const rules=await Promise.all(Array.from({length:20},()=>store.insertRuleWithinQuota({...base,rule_id:randomUUID(),watchlist_id:'list',condition_type:'new_transaction',threshold_value:null,delivery_channel:'in_app',webhook_id:null,enabled:true,rate_limit_per_hour:1,version:1},2)));expect(rules.filter(Boolean)).toHaveLength(2);});
 it('paginates all saved records without overlaps and rejects malformed page limits',async()=>{const store=new MemoryOwnerStore();useOwnerStore(store);for(let i=0;i<205;i++)await store.insertSavedQuery({...base,query_id:'00000000-0000-4000-8000-'+i.toString(16).padStart(12,'0'),title:'Saved'+i,sql_text:'SELECT '+i});const owner:any={owner_id:base.owner_id};const first=await queryStudioService.getSavedQueryPage(owner);expect(first.count).toBe(200);expect(first.complete).toBe(false);const second=await queryStudioService.getSavedQueryPage(owner,200,first.next_cursor!);expect(second.count).toBe(5);expect(second.complete).toBe(true);expect(new Set([...first.saved_queries,...second.saved_queries].map(row=>row.query_id)).size).toBe(205);await expect(queryStudioService.getSavedQueryPage(owner,1.5)).rejects.toMatchObject({status:400});await expect(queryStudioService.getSavedQueryPage(owner,100,'invalid')).rejects.toMatchObject({status:400});});
});
