import { Component, Inject, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { Subscription, of } from 'rxjs';
import { switchMap } from 'rxjs/operators';
import { LightningResilienceApiService } from './lightning-resilience.service';
import { RelativeUrlPipe } from '@app/shared/pipes/relative-url/relative-url.pipe';
@Component({selector:'app-lightning-resilience-overview',standalone:true,imports:[CommonModule,RouterModule,RelativeUrlPipe],template:`<div class="container-xl py-4"><h1 class="h2">Lightning Resilience</h1><nav class="d-flex flex-wrap gap-3 mb-4" aria-label="Lightning resilience"><a [routerLink]="'/lightning/resilience' | relativeUrl">Overview</a><a [routerLink]="'/lightning/resilience/htlcs' | relativeUrl">HTLC slots</a><a [routerLink]="'/lightning/resilience/onion-messages' | relativeUrl">Onion queues</a><a [routerLink]="'/lightning/resilience/simulate' | relativeUrl">Simulator</a><a [routerLink]="'/lightning/resilience/mitigations' | relativeUrl">Mitigations</a></nav><p *ngIf="loading" role="status">Loading owned evidence…</p><p *ngIf="loadError" role="alert" class="alert alert-warning">{{ loadError }}</p><section *ngIf="overview"><p class="alert alert-info">{{ overview.scope }}</p><p>Source: {{ overview.source.status }} <span *ngIf="overview.source.error">({{ overview.source.error }})</span></p><p>Observed: {{ overview.source.observed_at_utc ?? 'Unknown' }}</p><dl><dt>Monitored owned channels</dt><dd>{{ overview.total_channels_monitored ?? 'Unknown' }}</dd><dt>Slot utilization</dt><dd>{{ overview.average_slot_utilization_pct === null ? 'Unknown' : (overview.average_slot_utilization_pct | number:'1.0-2') + '%' }}</dd><dt>Channel health and congestion diagnosis</dt><dd>Not evaluated</dd><dt>Hold duration / incident detection</dt><dd>Unknown; historical telemetry is unavailable</dd></dl><h2 class="h5">Observed channels by slot utilization</h2><div class="table-responsive" tabindex="0"><table class="table"><thead><tr><th>Channel</th><th>Capacity (sats)</th><th>Slots used / capacity</th><th>Slot utilization</th><th>Assessment</th></tr></thead><tbody><tr *ngFor="let c of overview.top_congested_channels"><td><a [routerLink]="['/lightning/resilience/channel' | relativeUrl,c.short_channel_id]">{{ c.short_channel_id }}</a></td><td>{{ c.capacity_sats | number }}</td><td>{{ c.htlc_slots_in_use }} / {{ c.htlc_slot_capacity ?? 'Unknown' }}</td><td>{{ c.htlc_slot_utilization_pct === null ? 'Unknown' : (c.htlc_slot_utilization_pct | number:'1.0-2') + '%' }}</td><td>{{ c.resilience_band }}</td></tr></tbody></table></div><p *ngIf="!overview.top_congested_channels.length">No current channel observations to display.</p></section></div>`})
export class LightningResilienceOverviewComponent implements OnInit,OnDestroy {
 overview:any=null;loadError:string|null=null;loading=false;private subscription?:Subscription;
 constructor(@Inject(LightningResilienceApiService) private api:LightningResilienceApiService,@Inject(ChangeDetectorRef) private cdr:ChangeDetectorRef){}
 ngOnInit(){this.subscription=this.api.watch$(()=>this.api.getOverview$(),null).subscribe(s=>{this.overview=s.value;this.loadError=s.error;this.loading=s.loading;this.cdr.markForCheck();});}
 ngOnDestroy(){this.subscription?.unsubscribe();}
}
