import { describe,it,expect,vi } from 'vitest';
import { Subject,of } from 'rxjs';
import { ChangeDetectorRef,provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { renderApplication } from '@angular/platform-server';
import { provideRouter,convertToParamMap } from '@angular/router';
import { StateService } from '@app/services/state.service';
import { LightningResilienceApiService } from './lightning-resilience.service';
import { LightningResilienceSimulateComponent } from './lightning-resilience-simulate.component';
import { LightningResilienceChannelDetailComponent } from './lightning-resilience-channel-detail.component';
import { LightningResilienceOverviewComponent } from './lightning-resilience-overview.component';
const cdr={markForCheck:vi.fn()} as unknown as ChangeDetectorRef;
const state=()=>({isBrowser:false,network:'signet',env:{ROOT_NETWORK:'mainnet',BASE_MODULE:'mempool',NGINX_PROTOCOL:'http',NGINX_HOSTNAME:'localhost',NGINX_PORT:8999},networkChanged$:new Subject<string>()});
describe('Lightning evidence frontend',()=>{
 it('loads selected network, clears old results and survives source errors on later network changes',()=>{const s=state(),pending:Subject<any>[]=[];const http={get:vi.fn((_url:string)=>{const p=new Subject<any>();pending.push(p);return p;})};const api=new LightningResilienceApiService(http as any,s as any);const results:any[]=[];const sub=api.watch$(()=>api.getOverview$(),null).subscribe(v=>results.push(v));expect(http.get.mock.calls[0][0]).toContain('/signet/api/');pending[0].next({network:'signet'});s.network='mainnet';s.networkChanged$.next('mainnet');expect(results.at(-1).value).toBeNull();pending[0].next({stale:true});expect(results.at(-1).value).toBeNull();pending[1].error(Error('offline'));expect(results.at(-1).error).toBeTruthy();s.network='signet';s.networkChanged$.next('signet');pending[2].next({network:'signet'});expect(results.at(-1).value.network).toBe('signet');sub.unsubscribe();});
 it('submits the complete HTLC contract and discards results on edits, errors and network switches',()=>{const changes=new Subject<string>();let response=new Subject<any>();const api:any={networkChanged$:changes,simulate$:vi.fn(()=>response)};const c=new LightningResilienceSimulateComponent(api,cdr);c.ngOnInit();c.runSimulation();const body=api.simulate$.mock.calls[0][0];expect(body.attacker_htlc_count).toBe(20);expect(body.attacker_htlc_value_sats).toBe(2000);expect(body).not.toHaveProperty('attacker_slots');c.edit('attacker_htlc_count',0);response.next({old:true});expect(c.simulationResult).toBeNull();response=new Subject();c.runSimulation();response.error(Error('failed'));expect(c.simulating).toBe(false);expect(c.error).toBeTruthy();response=new Subject();c.runSimulation();changes.next('mainnet');response.next({oldNetwork:true});expect(c.simulationResult).toBeNull();expect(c.simulating).toBe(false);c.ngOnDestroy();});
 it('cancels old channel route requests and clears missing references',()=>{const routes=new Subject<any>();const pending=new Map<string,Subject<any>>(); const s=state();const http={get:vi.fn((url:string)=>{const p=new Subject();pending.set(url.split('/').at(-1)!,p);return p;})};const realApi=new LightningResilienceApiService(http as any,s as any);const c=new LightningResilienceChannelDetailComponent({paramMap:routes} as any,realApi,cdr);c.ngOnInit();routes.next(convertToParamMap({shortId:'1x2x3'}));routes.next(convertToParamMap({shortId:'4x5x6'}));pending.get('1x2x3')!.next({short_channel_id:'old'});expect(c.channel).toBeNull();pending.get('4x5x6')!.next({short_channel_id:'new'});expect(c.channel.short_channel_id).toBe('new');routes.next(convertToParamMap({}));expect(c.channel).toBeNull();expect(c.loadError).toContain('does not name');c.ngOnDestroy();});
 it('renders unknown telemetry without healthy counts or fabricated observations',async()=>{const s=state();const overview={scope:'Owned snapshot only',source:{status:'unavailable',error:'lightning-disabled',observed_at_utc:null},total_channels_monitored:null,average_slot_utilization_pct:null,top_congested_channels:[]};const html=await renderApplication(context=>bootstrapApplication(LightningResilienceOverviewComponent,{providers:[provideZonelessChangeDetection(),provideRouter([]),{provide:StateService,useValue:s},{provide:LightningResilienceApiService,useValue:{getOverview$:()=>of(overview),watch$:(load:any)=>of({value:overview,error:null,loading:false})}}]},context),{document:'<app-lightning-resilience-overview></app-lightning-resilience-overview>',url:'http://localhost/',allowedHosts:['localhost']});expect(html).toContain('Unknown');expect(html).toContain('Not evaluated');expect(html).not.toContain('81 Normal');expect(html).toContain('lightning-disabled');});
});
