import { Component, Inject, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { Subscription, of } from 'rxjs';
import { switchMap } from 'rxjs/operators';
import { LightningResilienceApiService } from './lightning-resilience.service';
import { RelativeUrlPipe } from '@app/shared/pipes/relative-url/relative-url.pipe';
@Component({selector:'app-lightning-resilience-channel-detail',standalone:true,imports:[CommonModule,RouterModule,RelativeUrlPipe],template:`<div class="container-xl py-4"><h1 class="h2">Owned Channel Diagnostics</h1><nav class="d-flex flex-wrap gap-3 mb-4" aria-label="Lightning resilience"><a [routerLink]="'/lightning/resilience' | relativeUrl">Overview</a><a [routerLink]="'/lightning/resilience/htlcs' | relativeUrl">HTLC slots</a><a [routerLink]="'/lightning/resilience/onion-messages' | relativeUrl">Onion queues</a><a [routerLink]="'/lightning/resilience/simulate' | relativeUrl">Simulator</a><a [routerLink]="'/lightning/resilience/mitigations' | relativeUrl">Mitigations</a></nav><p *ngIf="loading" role="status">Loading owned evidence…</p><p *ngIf="loadError" role="alert" class="alert alert-warning">{{ loadError }}</p><section *ngIf="channel"><p>{{ channel.scope }}</p><p>Observed: {{ channel.observed_at_utc }}</p><dl><dt>Channel</dt><dd>{{ channel.short_channel_id }}</dd><dt>Capacity</dt><dd>{{ channel.capacity_sats | number }} sats</dd><dt>Pending aggregate value</dt><dd>{{ channel.pending_htlc_value_sats | number }} sats</dd><dt>Incoming slots</dt><dd>{{ channel.incoming.slots_in_use }} / {{ channel.incoming.slot_capacity ?? 'Unknown' }}</dd><dt>Outgoing slots</dt><dd>{{ channel.outgoing.slots_in_use }} / {{ channel.outgoing.slot_capacity ?? 'Unknown' }}</dd><dt>Hold duration and failure rate</dt><dd>Unknown</dd><dt>Reputation / fast-lane deployment</dt><dd>Unknown</dd></dl><p class="text-break">Local node: <a [routerLink]="['/lightning/resilience/node' | relativeUrl,channel.node1_pubkey]">{{ channel.node1_pubkey }}</a></p><p class="text-break">Remote node: <a [routerLink]="['/lightning/resilience/node' | relativeUrl,channel.node2_pubkey]">{{ channel.node2_pubkey }}</a></p></section></div>`})
export class LightningResilienceChannelDetailComponent implements OnInit,OnDestroy {
 channel:any=null;loadError:string|null=null;loading=false;private subscription?:Subscription;
 constructor(@Inject(ActivatedRoute) private route:ActivatedRoute,@Inject(LightningResilienceApiService) private api:LightningResilienceApiService,@Inject(ChangeDetectorRef) private cdr:ChangeDetectorRef){}
 ngOnInit(){this.subscription=this.route.paramMap.pipe(switchMap(params=>{const id=params.get('shortId');return id?this.api.watch$(()=>this.api.getChannel$(id),null):of({value:null,error:'This address does not name a channel.',loading:false});})).subscribe(s=>{this.channel=s.value;this.loadError=s.error;this.loading=s.loading;this.cdr.markForCheck();});}
 ngOnDestroy(){this.subscription?.unsubscribe();}
}
