import {describe,it,expect,vi,afterEach} from 'vitest';
import {Subject,of,throwError} from 'rxjs';
import {DeveloperPlatformComponent} from './developer-platform.component';
import {OwnerKeyService} from './owner-key.service';
afterEach(()=>vi.unstubAllGlobals());
function setup(){const storage=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});const owner=new OwnerKeyService();const ownerRequest=new Subject<any>();const mint=new Subject<any>();const keys:Subject<any>[]=[];const api:any={createOwner$:()=>ownerRequest,generateDeveloperKey$:()=>mint,getDeveloperKeys$:()=>{const s=new Subject<any>();keys.push(s);return s;},getWebhooks$:()=>throwError(()=>({status:503})),getDeveloperUsage$:()=>of(null)};const c=new DeveloperPlatformComponent(api,owner,{markForCheck:vi.fn()} as any);c.ngOnInit();return {c,owner,ownerRequest,mint,keys,storage};}
describe('developer credential ownership',()=>{
 it('forget cancels a pending creation and cannot reinstall its credential',()=>{const {c,owner,ownerRequest,storage}=setup();c.ownerName='Disposable';c.createOwner();c.forgetKey();ownerRequest.next({secret_key:'uip_live_disposable'});expect(owner.key).toBeNull();expect(storage.size).toBe(0);expect(c.generatedKeySecret).toBeNull();expect(ownerRequest.observed).toBe(false);c.ngOnDestroy();});
 it('switching key clears prior owner data and cancels old secret/read completions',()=>{const {c,owner,mint,keys}=setup();c.pastedKey='uip_live_disposable_a';c.useKey();const old=keys.at(-1)!;c.newKeyLabel='Disposable';c.createKey();c.generatedKeySecret='disposable';c.generatedWebhookSecret='disposable';c.attempts={old:[{}]};c.pastedKey='uip_live_disposable_b';c.useKey();old.next({keys:[{owner_id:'old'}]});mint.next({secret_key:'uip_live_disposable_old'});expect(owner.key).toBe('uip_live_disposable_b');expect(c.keys).toEqual([]);expect(c.attempts).toEqual({});expect(c.generatedKeySecret).toBeNull();expect(c.generatedWebhookSecret).toBeNull();expect(old.observed).toBe(false);expect(mint.observed).toBe(false);expect(c.webhookError).toContain('unavailable');c.ngOnDestroy();});
 it('successful owner creation keeps one-time secret until destruction without deleting held key',()=>{const {c,owner,ownerRequest,storage}=setup();c.ownerName='Disposable';c.createOwner();ownerRequest.next({secret_key:'uip_live_disposable',owner_id:'owned'});expect(c.generatedKeySecret).toBe(owner.key);expect(c.ownerId).toBe('owned');c.ngOnDestroy();expect(c.generatedKeySecret).toBeNull();expect(c.generatedWebhookSecret).toBeNull();expect(owner.key).toBe('uip_live_disposable');expect(storage.size).toBe(1);});
 it('external credential changes cancel reads and clear secrets',()=>{const {c,owner,keys}=setup();c.pastedKey='uip_live_disposable_a';c.useKey();const pending=keys.at(-1)!;c.generatedKeySecret='disposable';owner.clear();expect(pending.observed).toBe(false);expect(c.generatedKeySecret).toBeNull();expect(c.hasKey).toBe(false);c.ngOnDestroy();});
});
