import { ChangeDetectorRef,provideZonelessChangeDetection } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { bootstrapApplication } from '@angular/platform-browser';
import { renderApplication } from '@angular/platform-server';
import { Subject,of } from 'rxjs';
import { describe,it,expect,vi } from 'vitest';
import { StateService } from '@app/services/state.service';
import { RelayObservatoryComponent } from './relay-observatory.component';
function setup(){const network=new Subject<string>();const pending=new Subject<any>();const state:any={isBrowser:false,network:'signet',env:{NGINX_PROTOCOL:'http',NGINX_HOSTNAME:'localhost',NGINX_PORT:8999,ROOT_NETWORK:'mainnet'},networkChanged$:network};const http={get:vi.fn((url:string)=>url.includes('/transactions/')?pending:of({recent_propagation_sample:[]}))};const c=new RelayObservatoryComponent(http as any,state,{markForCheck:vi.fn()} as unknown as ChangeDetectorRef);c.ngOnInit();return{c,http,state,network,pending};}
describe('relay UI evidence ownership',()=>{
 it('uses selected network, recent observed samples only, and clears stale searches',()=>{const {c,http,pending,network,state}=setup();c.loadSampleTx();expect(c.searchTxid).toBe('');c.editTxid('ab'.repeat(32));c.searchTx();expect(http.get.mock.calls.at(-1)![0]).toContain('/signet/api/v1/intelligence/relay/transactions/');c.editTxid('bc'.repeat(32));pending.next({txid:'old'});expect(c.activeLifecycle).toBeNull();c.searchTx();state.network='mainnet';network.next('mainnet');pending.next({txid:'old-network'});expect(c.activeLifecycle).toBeNull();expect(http.get.mock.calls.at(-1)![0]).not.toContain('/signet/');c.ngOnDestroy();});
 it('renders departures as unknown causes and does not invent latency or acceptance',async()=>{const html=await renderApplication(async context=>{const app=await bootstrapApplication(RelayObservatoryComponent,{providers:[provideZonelessChangeDetection(),{provide:HttpClient,useValue:{get:()=>of(null)}},{provide:StateService,useValue:{isBrowser:false,network:'mainnet',env:{NGINX_PROTOCOL:'http',NGINX_HOSTNAME:'localhost',NGINX_PORT:80,ROOT_NETWORK:'mainnet'},networkChanged$:new Subject<string>()}}]},context);const c=app.components[0].instance as RelayObservatoryComponent;c.overview=null;c.activeLifecycle={scope:'Local poll detections only',first_observed_utc:'2026-09-15T00:00:00Z',retention:{events_pruned:0},events:[{source_sequence:2,observed_at_utc:'2026-09-15T00:00:01Z',payload:{presence:'left_mempool',previous_complete_poll_utc:null,complete_poll:true}}]};app.components[0].changeDetectorRef.detectChanges();return app;},{document:'<html><body><app-relay-observatory></app-relay-observatory></body></html>',url:'http://localhost/',allowedHosts:['localhost']});expect(html).toContain('Left local mempool; cause unknown');expect(html).toContain('Unknown / observation gap');expect(html).not.toContain('Trans-continental');expect(html).not.toContain('>Accepted<');});
});
