import { Component, OnInit, OnDestroy, Inject, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { StateService } from '@app/services/state.service';
@Component({selector:'app-relay-observatory',standalone:true,imports:[CommonModule,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,
 template:`<section class="container-xl py-4"><h1>Relay and policy observatory</h1><p>Owned node peer metadata and local mempool detections. Multi-sensor propagation, calibrated clocks and transaction transport attribution require additional observations.</p>
 <button class="btn btn-outline-secondary mb-3" (click)="refreshAll()">Refresh observations</button>
 <p *ngIf="overviewError" role="alert" class="text-danger">{{ overviewError }}</p>
 <section *ngIf="overview" class="card p-3 mb-4"><h2 class="h5">{{ overview.online_sensors }} owned sensor · {{ overview.network }}</h2><p>{{ overview.scope }}</p>
 <dl><dt>Core observation</dt><dd>{{ overview.source.observed_at_utc | date:'medium' }} · {{ overview.source.age_ms }} ms old</dd><dt>Poll collection</dt><dd>{{ overview.collection.status }} · {{ overview.collection.retained_transactions }} retained transactions · {{ overview.collection.dropped_events }} dropped events</dd><dt>Connected peers using BIP324</dt><dd>{{ overview.transport.bip324_peers }} of {{ overview.transport.known_transport_peers }} with known transport; {{ overview.transport.unknown_transport_peers }} unknown</dd><dt>Propagation latency</dt><dd>Not measured</dd><dt>Erlay capability</dt><dd>Not observed</dd><dt>Clock calibration</dt><dd>Unknown · {{ overview.collection.clock_regressions }} local clock regressions detected</dd></dl>
 <p *ngFor="let sensor of overview.sensors">{{ sensor.client_version }} · minimum relay fee {{ sensor.min_relay_feerate == null ? 'Unknown' : sensor.min_relay_feerate + ' sat/vB' }} · full RBF {{ sensor.full_rbf == null ? 'Unknown' : sensor.full_rbf ? 'Enabled' : 'Disabled' }}</p>
 </section>
 <section class="card p-3 mb-4"><h2 class="h5">Transaction detection history</h2><label for="relay-txid">Transaction ID</label><input id="relay-txid" class="form-control font-monospace mb-2" [ngModel]="searchTxid" (ngModelChange)="editTxid($event)"><div><button class="btn btn-primary me-2" [disabled]="loadingSearch || !searchTxid.trim()" (click)="searchTx()">Inspect</button><button class="btn btn-outline-secondary" [disabled]="!overview?.recent_propagation_sample?.length" (click)="loadSampleTx()">Use recent observed transaction</button></div>
 <p *ngIf="searchError" role="alert" class="text-danger mt-2">{{ searchError }}</p>
 <article *ngIf="activeLifecycle" class="mt-3"><p>{{ activeLifecycle.scope }}</p><p>First local detection: {{ activeLifecycle.first_observed_utc | date:'medium' }}. {{ activeLifecycle.retention.events_pruned }} older lifecycle events pruned.</p><p>Arrival time, propagation spread, policy rejection cause and per-transaction transport: not measured.</p><div class="table-responsive"><table class="table"><thead><tr><th>Sequence</th><th>Detected locally</th><th>Observation</th><th>Previous complete poll</th><th>Poll complete</th></tr></thead><tbody><tr *ngFor="let event of activeLifecycle.events"><td>{{ event.source_sequence }}</td><td>{{ event.observed_at_utc | date:'medium' }}</td><td>{{ event.payload.presence === 'present' ? 'Present in local mempool' : 'Left local mempool; cause unknown' }}</td><td>{{ event.payload.previous_complete_poll_utc ? (event.payload.previous_complete_poll_utc | date:'medium') : 'Unknown / observation gap' }}</td><td>{{ event.payload.complete_poll ? 'Yes' : 'No' }}</td></tr></tbody></table></div></article></section>
 <section class="card p-3 mb-4"><h2 class="h5">Policy comparison</h2><p *ngIf="policyError" class="text-danger">{{ policyError }}</p><p *ngIf="policy">{{ policy.scope }}</p><p>Multiple independently observed sensors and policy probes are required for a divergence verdict.</p></section>
 <section class="card p-3"><h2 class="h5">Live local detections</h2><p>{{ streamStatus }}</p><p>Live events only. Disconnections do not replay missing observations.</p><ul><li *ngFor="let event of liveEvents"><button class="btn btn-link font-monospace text-break" (click)="inspectEvent(event.payload.txid)">{{ event.payload.txid }}</button> {{ event.payload.presence }} · {{ event.observed_at_utc | date:'mediumTime' }}</li></ul></section></section>`})
export class RelayObservatoryComponent implements OnInit,OnDestroy{
 overview:any=null;overviewError:string|null=null;loadingOverview=false;activeLifecycle:any=null;loadingSearch=false;searchError:string|null=null;searchTxid='';policy:any=null;policyError:string|null=null;liveEvents:any[]=[];streamStatus='Not connected';
 private revision=0;private searchRevision=0;private requests:Subscription[]=[];private searchRequest?:Subscription;private network?:Subscription;private stream:EventSource|null=null;
 constructor(@Inject(HttpClient)private http:HttpClient,@Inject(StateService)private state:StateService,@Inject(ChangeDetectorRef)private cdr:ChangeDetectorRef){}
 ngOnInit():void{let emitted=false;this.network=this.state.networkChanged$.subscribe(()=>{emitted=true;this.refreshAll();});if(!emitted)this.refreshAll();}
 private url(path:string):string{const origin=this.state.isBrowser?'':this.state.env.NGINX_PROTOCOL+'://'+this.state.env.NGINX_HOSTNAME+':'+this.state.env.NGINX_PORT;const network=this.state.network;return origin+(network&&network!==this.state.env.ROOT_NETWORK?'/'+network:'')+'/api/v1/intelligence/relay/'+path;}
 private clearSearch():void{this.searchRevision++;this.searchRequest?.unsubscribe();this.activeLifecycle=null;this.searchError=null;this.loadingSearch=false;}
 refreshAll():void{this.revision++;const revision=this.revision;this.requests.forEach(s=>s.unsubscribe());this.requests=[];this.stream?.close();this.stream=null;this.clearSearch();this.overview=null;this.overviewError=null;this.policy=null;this.policyError=null;this.liveEvents=[];this.loadingOverview=true;
 this.requests.push(this.http.get<any>(this.url('overview')).subscribe({next:value=>{if(revision!==this.revision)return;this.overview=value;this.loadingOverview=false;this.cdr.markForCheck();},error:error=>{if(revision!==this.revision)return;this.overviewError=error?.error?.error||'Owned relay source unavailable.';this.loadingOverview=false;this.cdr.markForCheck();}}));
 this.requests.push(this.http.get<any>(this.url('policy-differences')).subscribe({next:value=>{if(revision!==this.revision)return;this.policy=value;this.cdr.markForCheck();},error:error=>{if(revision!==this.revision)return;this.policyError=error?.error?.error||'Policy observation unavailable.';this.cdr.markForCheck();}}));
 this.streamStatus='Live stream unavailable in this rendering context.';
 if(this.state.isBrowser&&typeof EventSource!=='undefined'){const network=this.state.network||this.state.env.ROOT_NETWORK||'mainnet';this.stream=new EventSource(this.url('stream'));this.streamStatus='Connecting';this.stream.onopen=()=>{if(revision===this.revision){this.streamStatus='Connected';this.cdr.markForCheck();}};this.stream.onerror=()=>{if(revision===this.revision){this.streamStatus='Disconnected; reconnecting. Events during the gap are not replayed.';this.cdr.markForCheck();}};this.stream.addEventListener('intelligence.relay.transaction',(message:MessageEvent)=>{if(revision!==this.revision)return;try{const event=JSON.parse(message.data);if(event.network!==network||!event.payload||!/^[0-9a-f]{64}$/.test(event.payload.txid))return;this.liveEvents=[event,...this.liveEvents].slice(0,20);this.cdr.markForCheck();}catch{/* Ignore malformed stream frames. */}});}
 this.cdr.markForCheck();}
 editTxid(value:string):void{this.clearSearch();this.searchTxid=value;this.cdr.markForCheck();}
 loadSampleTx():void{const txid=this.overview?.recent_propagation_sample?.[0]?.txid;if(txid)this.inspectEvent(txid);}
 inspectEvent(txid:string):void{this.editTxid(txid);this.searchTx();}
 searchTx():void{this.clearSearch();const txid=this.searchTxid.trim();if(!/^[0-9a-fA-F]{64}$/.test(txid)){this.searchError='Enter a 64-character hexadecimal transaction ID.';this.cdr.markForCheck();return;}const revision=this.searchRevision;this.loadingSearch=true;this.searchRequest=this.http.get<any>(this.url('transactions/'+txid)).subscribe({next:value=>{if(revision!==this.searchRevision)return;this.activeLifecycle=value;this.loadingSearch=false;this.cdr.markForCheck();},error:error=>{if(revision!==this.searchRevision)return;this.searchError=error?.error?.error||'Transaction not retained by this observer.';this.loadingSearch=false;this.cdr.markForCheck();}});}
 ngOnDestroy():void{this.revision++;this.clearSearch();this.requests.forEach(s=>s.unsubscribe());this.network?.unsubscribe();this.stream?.close();}
}
