import { Component,Inject,OnInit,OnDestroy,ChangeDetectionStrategy,ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { UtxoEvidenceService,UtxoEvidence } from '../utxo-set/utxo-evidence.service';
@Component({selector:'app-utxo-intelligence',standalone:true,imports:[CommonModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="container-xl py-4"><h1>UTXO Set and Supply Intelligence</h1><p>Owned Core checkpoints and independently reconciled outpoint projections. Unknown cohorts are not estimated from supply totals.</p>
<p *ngIf="loading" role="status">Reading owned UTXO evidence…</p><p *ngIf="loadError" role="alert" class="alert alert-warning">{{ loadError }}</p>
<section *ngIf="overview"><h2 class="h4">Owned node checkpoint</h2><p>{{ overview.scope }}</p><dl><dt>Block</dt><dd>{{ overview.block_height }} <code class="text-break">{{ overview.block_hash }}</code></dd><dt>Unspent outputs</dt><dd>{{ overview.total_utxos | number }}</dd><dt>Value in unspent outputs</dt><dd>{{ overview.total_amount_sats | number }} sats</dd><dt>Core MuHash</dt><dd class="text-break"><code>{{ overview.muhash }}</code></dd><dt>Observed</dt><dd>{{ overview.observed_at_utc }}</dd><dt>Dormant ten-year value</dt><dd>{{ overview.dormant_10yr_sats ?? 'Unknown without age projection' }}</dd></dl></section>
<section class="my-4"><h2 class="h4">Independent reconciliation</h2><p *ngIf="states.reconciliation?.kind !== 'available'">{{ states.reconciliation?.message ?? 'Checking projection availability…' }}</p><ng-container *ngIf="reconciliation"><p>{{ reconciliation.reconciled === true ? 'Core MuHash, output count and exact satoshi value match the projection at this block.' : 'Not independently reconciled.' }}</p><p>Core block: {{ reconciliation.block_height }}; projection block: {{ reconciliation.projection_height ?? 'Unavailable' }}.</p><p>No finality or guaranteed reorganization depth is implied.</p></ng-container></section>
<section class="my-4"><h2 class="h4">Complete cohort partitions</h2><p *ngIf="states.cohorts?.kind !== 'available'">{{ states.cohorts?.message ?? 'Checking cohort availability…' }}</p><ng-container *ngIf="cohorts"><p>Reconciled block {{ cohorts.block_height }}. {{ cohorts.scope }}</p><div class="table-responsive" *ngFor="let group of cohortGroups"><h3 class="h5">{{ group.title }}</h3><table class="table"><thead><tr><th>Band</th><th>Outputs</th><th>Satoshis</th><th>Share of UTXO value</th></tr></thead><tbody><tr *ngFor="let c of cohorts[group.key]"><td>{{ c[group.label] }}</td><td>{{ c.utxo_count | number }}</td><td>{{ c.total_sats | number }}</td><td>{{ c.percent_of_supply | number:'1.0-3' }}%</td></tr></tbody></table></div></ng-container></section>
<section class="my-4"><h2 class="h4">Spend-cost scenarios</h2><p *ngIf="states.thresholds?.kind !== 'available'">{{ states.thresholds?.message ?? 'Checking spend-cost availability…' }}</p><p *ngIf="thresholds.length">{{ thresholds[0].scope }}</p><div class="table-responsive" *ngIf="thresholds.length"><table class="table"><thead><tr><th>Fee (sat/vB)</th><th>Outputs at or below modeled input cost</th><th>Satoshis</th><th>Outputs with unknown spend cost</th></tr></thead><tbody><tr *ngFor="let t of thresholds"><td>{{ t.feerate_sats_vb }}</td><td>{{ t.uneconomical_utxo_count | number }}</td><td>{{ t.uneconomical_sats | number }}</td><td>{{ t.unknown_spend_cost_utxo_count | number }}</td></tr></tbody></table></div></section>
<section><h2 class="h4">Spend transitions</h2><p *ngIf="states.transitions?.kind !== 'available'">{{ states.transitions?.message ?? 'Checking transition availability…' }}</p><div class="table-responsive" *ngIf="transitions.length"><table class="table"><thead><tr><th>Height</th><th>Created outputs / sats</th><th>Spent outputs / sats</th><th>Destroyed age (sat-seconds)</th></tr></thead><tbody><tr *ngFor="let t of transitions"><td>{{ t.height }}</td><td>{{ t.created_count }} / {{ t.created_sats }}</td><td>{{ t.spent_count }} / {{ t.spent_sats }}</td><td class="text-break">{{ t.coin_age_destroyed_sat_seconds }}</td></tr></tbody></table></div></section></div>`})
export class UtxoIntelligenceComponent implements OnInit,OnDestroy {
 overview:any=null;cohorts:any=null;thresholds:any[]=[];transitions:any[]=[];reconciliation:any=null;loading=false;loadError:string|null=null;states:Record<string,UtxoEvidence>={};private subscriptions:Subscription[]=[];
 cohortGroups=[{title:'Script types',key:'script_types',label:'script_type'},{title:'Age',key:'age_cohorts',label:'age_band'},{title:'Value',key:'value_cohorts',label:'value_band'}];
 constructor(@Inject(UtxoEvidenceService) private api:UtxoEvidenceService,@Inject(ChangeDetectorRef) private cdr:ChangeDetectorRef){}
 ngOnInit(){for(const [key,path] of [['overview','overview'],['cohorts','cohorts'],['thresholds','economic-thresholds'],['reconciliation','reconciliation'],['transitions','spend-transitions']]){this.subscriptions.push(this.api.watch$('/api/v1/intelligence/utxo/'+path).subscribe(s=>{this.states[key]=s;switch(key){case 'overview':this.overview=s.value;this.loading=s.kind==='loading';this.loadError=s.message;break;case 'cohorts':this.cohorts=s.value;break;case 'thresholds':this.thresholds=s.value?.thresholds??[];break;case 'reconciliation':this.reconciliation=s.value;break;case 'transitions':this.transitions=s.value?.transitions??[];}this.cdr.markForCheck();}));}}
 ngOnDestroy(){this.subscriptions.forEach(s=>s.unsubscribe());}
}
