import {describe,it,expect,vi} from 'vitest';
import {BehaviorSubject,Subject,of,throwError} from 'rxjs';
import {WatchlistsComponent} from './watchlists.component';
describe('watchlist owner and network ownership',()=>{
 function setup(){const key=new BehaviorSubject<string|null>('disposable-a');const owner:any={key$:key,get key(){return key.value;}};const network=new Subject<string>();const state:any={network:'mainnet',networkChanged$:network};const reads:Subject<any>[]=[];const mutations=new Subject<any>();const notifications=new Subject<any>();const api:any={getWatchlists$:vi.fn(()=>{const s=new Subject<any>();reads.push(s);return s;}),getWebhooks$:()=>throwError(()=>({status:503})),getWatchlistNotifications$:()=>notifications,createWatchlist$:()=>mutations};const c=new WatchlistsComponent(api,owner,{markForCheck:vi.fn()} as any,state);c.ngOnInit();return {c,key,network,state,reads,mutations,notifications,api};}
 it('cancels prior-owner reads and writes, clears private input on owner and network changes',()=>{const {c,key,network,state,reads,mutations,api}=setup();const old=reads.at(-1)!;c.newName='Disposable';c.create();c.entityRaw={old:'private observation'};key.next('disposable-b');const count=api.getWatchlists$.mock.calls.length;old.next({watchlists:[{watchlist_id:'old'}]});mutations.next({ok:true});expect(api.getWatchlists$).toHaveBeenCalledTimes(count);expect(c.watchlists).toEqual([]);expect(c.entityRaw).toEqual({});expect(mutations.observed).toBe(false);reads.at(-1)!.next({watchlists:[{watchlist_id:'new'}]});expect(c.watchlists).toHaveLength(1);state.network='signet';network.next('signet');expect(c.watchlists).toEqual([]);expect(c.webhookError).toContain('unavailable');c.ngOnDestroy();});
 it('does not show false empty notifications on failure and releases every pending request on destroy',()=>{const {c,notifications,reads,key}=setup();notifications.error({status:503});expect(c.notificationError).toContain('Failed');expect(c.loadingNotifications).toBe(false);const pending=reads.at(-1)!;c.ngOnDestroy();expect(pending.observed).toBe(false);expect(key.observed).toBe(false);expect(c.watchlists).toEqual([]);expect((c as any).requests.size).toBe(0);});
 it('repeated loads replace pending reads rather than accumulating subscriptions',()=>{const {c,reads}=setup();for(let i=0;i<20;i++)c.load();expect(reads.filter(s=>s.observed)).toHaveLength(1);expect((c as any).requests.size).toBeLessThanOrEqual(2);c.ngOnDestroy();});
});
