import {describe,it,expect,vi} from 'vitest';
import {of,Subject} from 'rxjs';
import {OffchainApiService} from './offchain.service';
import {publicManifest,PublicManifestComponent} from './public-manifest.component';
const manifest={signature_scheme:'schnorr',protocol:'mercury_statechain',operator_public_key:'02'+'ab'.repeat(32),signature:'ab'.repeat(64),effective_from:'2026-01-01T00:00:00Z',expires_at:'2099-01-01T00:00:00Z',endpoints:{clearnet:'https://example.com'}};
describe('offchain public reference boundaries',()=>{
 it('maps real registry shape with unknown health and filters protocol locally',()=>{const get=vi.fn(()=>of([{operator_id:'a',protocol:'mercury_statechain',display_name:'Reference',endpoints:{clearnet:'https://example.com'},health:'healthy'},{operator_id:'b',protocol:'teleport_coinswap',endpoints:{clearnet:'https://example.com'}}]));const api=new OffchainApiService({get} as any,{isBrowser:true} as any);api.getOperators$('mercury_statechain').subscribe(rows=>{expect(rows).toHaveLength(1);expect(rows[0].health).toBe('unknown');expect(rows[0].published_terms.min_amount_sat).toBeNull();});});
 it('rejects secret fields and credential-bearing URLs before any request',()=>{expect(()=>publicManifest(JSON.stringify({...manifest,private_key:'test'}))).toThrow();expect(()=>publicManifest(JSON.stringify({...manifest,endpoints:{clearnet:'https://user:pass@example.com'}}))).toThrow();expect(publicManifest(JSON.stringify(manifest)).signature_scheme).toBe('schnorr');});
 it('clears signature verdict on edits and never authenticates supplied operator identity',()=>{const pending=new Subject<any>();const c=new PublicManifestComponent({verifyManifest$:()=>pending} as any);c.text=JSON.stringify(manifest);c.verify();pending.next({scheme:'schnorr',signature_valid:true,verified:true,operator_authenticated:true,verification_scope:'claimed'});expect(c.report).toBeNull();c.verify();pending.next({scheme:'schnorr',signature_valid:true,verified:true,operator_authenticated:null,verification_scope:'Signature only'});expect(c.report.signature_valid).toBe(true);c.clear();expect(c.report).toBeNull();expect(pending.observed).toBe(false);c.verify();c.ngOnDestroy();expect(pending.observed).toBe(false);expect(c.text).toBe('');});
});
