import {describe,it,expect,vi} from 'vitest';
import {BehaviorSubject,Subject,of} from 'rxjs';
import {CollaborativePrivacyInspectComponent as Inspect} from './collaborative-privacy-inspect.component';
import {CollaborativePrivacyCoordinatorsComponent as Coordinators} from './collaborative-privacy-coordinators.component';
import {CollaborativePrivacyFidelityBondsComponent as Bonds} from './collaborative-privacy-fidelity-bonds.component';
import {CollaborativePrivacyApiService as Api} from './collaborative-privacy.service';
describe('collaborative evidence boundaries',()=>{
 it('keeps unavailable entropy local and requires protocol package',()=>{const p=new Subject(),send=vi.fn(()=>p),c=new Inspect({verifyPublicPackage$:send} as any);c.txid='aa';c.inspect();expect(send).not.toHaveBeenCalled();c.packageText='{"txid":"aa"}';c.verifyPackage();expect(send).not.toHaveBeenCalled();c.packageText='{"protocol":"wabisabi"}';c.verifyPackage();expect(send).toHaveBeenCalledWith({protocol:'wabisabi'});p.error({status:503});expect(c.analysisResult).toBeNull();expect(c.loadError).toContain('unavailable');});
 it('cancels verification on edit/network/destroy',()=>{const n=new BehaviorSubject('signet'),p=new Subject(),c=new Inspect({networkChanged$:n,verifyPublicPackage$:()=>p} as any);c.ngOnInit();c.packageText='{"protocol":"wabisabi"}';c.verifyPackage();c.clear();expect(p.observed).toBe(false);c.verifyPackage();n.next('regtest');expect(p.observed).toBe(false);c.verifyPackage();c.ngOnDestroy();expect(p.observed).toBe(false);expect(c.packageText).toBe('');});
 it.each(['coordinators','bonds'])('clears %s across network/destroy',kind=>{const n=new BehaviorSubject('signet'),p=new Subject(),api={networkChanged$:n,getCoordinators$:()=>p,getFidelityBonds$:()=>p};const c:any=kind==='coordinators'?new Coordinators(api as any):new Bonds(api as any);c.ngOnInit();p.next([{status:'offline'}]);expect(c[kind]).toHaveLength(1);n.next('regtest');expect(c[kind]).toEqual([]);c.ngOnDestroy();expect(p.observed).toBe(false);});
 it('unwraps catalogue envelope and rejects unbound observation',()=>{const get=vi.fn(()=>of<any>({protocols:[{protocol_id:'wabisabi'}]}));const a=new Api({get} as any,{network:'signet',env:{ROOT_NETWORK:'signet'},networkChanged$:new Subject()} as any);a.getProtocols$().subscribe(r=>expect(r[0].protocol_id).toBe('wabisabi'));expect(get).toHaveBeenCalledWith('/api/v1/intelligence/collaborative/protocols');get.mockReturnValue(of({coordinators:[]}));let err:any;a.getCoordinators$().subscribe({error:e=>err=e});expect(err.message).toContain('network');});
});
