// @vitest-environment jsdom
import 'zone.js';
import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {signal} from '@angular/core';import {TestBed} from '@angular/core/testing';import {BrowserDynamicTestingModule,platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';import {ActivatedRoute,convertToParamMap} from '@angular/router';import {BehaviorSubject,Subject} from 'rxjs';
import {EphemeralPortfolioComponent} from './ephemeral-portfolio.component';import {PortfolioV2ApiService} from '../data/portfolio-v2-api.service';import {PortfolioSessionService} from '../stores/session.service';
beforeAll(()=>TestBed.initTestEnvironment(BrowserDynamicTestingModule,platformBrowserDynamicTesting()));afterEach(()=>TestBed.resetTestingModule());
function fixture(){const params=new BehaviorSubject(convertToParamMap({chain:'bitcoin',network:'mainnet',address:'first'}));const requests:any[]=[];const request=(kind:string)=>(chain:string,network:string,address:string)=>{const subject=new Subject<any>();requests.push({kind,chain,network,address,subject});return subject;};const api={getSummary$:vi.fn(request('summary')),getHoldings$:vi.fn(request('holdings')),getActivity$:vi.fn(request('activity'))};TestBed.configureTestingModule({providers:[{provide:ActivatedRoute,useValue:{paramMap:params}},{provide:PortfolioV2ApiService,useValue:api},{provide:PortfolioSessionService,useValue:{valuesHidden:signal(false)}}]});TestBed.overrideComponent(EphemeralPortfolioComponent,{set:{template:'',imports:[]}});const view=TestBed.createComponent(EphemeralPortfolioComponent);view.detectChanges();return {view,component:view.componentInstance,params,requests};}
function reply(request:any){const context={chain:request.chain,network:request.network,address:request.address},envelope={...context,chainTip:null};const value=request.kind==='summary'?{account:context,envelope,schemaVersion:'universe-portfolio-v2-summary-v1',aggregateState:'proven'}:request.kind==='holdings'?{account:context,envelope,schemaVersion:'universe-portfolio-v2-holdings-v1',sourceState:'proven',holdings:[],nextCursor:null}:{...context,account:context,schemaVersion:'universe-portfolio-activity-v2',sourceState:'proven',checkpoint:null,events:[],nextCursor:null};request.subject.next(value);request.subject.complete();}
async function complete(f:ReturnType<typeof fixture>,address:string){reply(f.requests.find(r=>r.address===address&&r.kind==='summary'));await vi.waitFor(()=>expect(f.requests.filter(r=>r.address===address)).toHaveLength(3));f.requests.filter(r=>r.address===address&&r.kind!=='summary').forEach(reply);await vi.waitFor(()=>expect(f.component.summary()?.account.address).toBe(address));}
it('route changes clear accepted evidence and dispatch captured network context',async()=>{const f=fixture();await complete(f,'first');f.params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(f.component.summary()).toBeNull();expect(f.component.holdings()).toBeNull();expect(f.component.failure()).toBe('');await complete(f,'second');expect(f.requests.filter(r=>r.address==='second').map(r=>r.network)).toEqual(['signet','signet','signet']);});
it('cancels old pending pages and destroy cancels the new summary without publication',async()=>{const f=fixture();reply(f.requests[0]);await vi.waitFor(()=>expect(f.requests).toHaveLength(3));expect(f.requests.slice(1).every(r=>r.subject.observed)).toBe(true);f.params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(f.requests.slice(0,3).every(r=>!r.subject.observed)).toBe(true);f.requests.slice(1,3).forEach(reply);expect(f.component.summary()).toBeNull();expect(f.requests[3].subject.observed).toBe(true);f.view.destroy();expect(f.requests[3].subject.observed).toBe(false);reply(f.requests[3]);await Promise.resolve();expect(f.component.summary()).toBeNull();});
it('summary errors remain sanitized and a later address is retryable',async()=>{const f=fixture();f.requests[0].subject.error(Error('private detail'));await vi.waitFor(()=>expect(f.component.failure()).toContain('could not be read'));expect(f.component.failure()).not.toContain('private detail');f.params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(f.component.failure()).toBe('');await complete(f,'second');});
