// @vitest-environment jsdom
import 'zone.js';import {afterEach,beforeAll,expect,it,vi} from 'vitest';
import {signal} from '@angular/core';import {TestBed} from '@angular/core/testing';import {BrowserDynamicTestingModule,platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';import {ActivatedRoute,convertToParamMap} from '@angular/router';import {BehaviorSubject,Subject} from 'rxjs';
import {EphemeralPortfolioComponent} from './ephemeral-portfolio.component';import {PortfolioV2ApiService} from '../data/portfolio-v2-api.service';import {PortfolioSessionService} from '../stores/session.service';
beforeAll(()=>TestBed.initTestEnvironment(BrowserDynamicTestingModule,platformBrowserDynamicTesting()));afterEach(()=>TestBed.resetTestingModule());
function fixture(){const params=new BehaviorSubject(convertToParamMap({chain:'bitcoin',network:'mainnet',address:'first'}));const requests:any[]=[];const request=(kind:string)=>(chain:string,network:string,address:string)=>{const subject=new Subject<any>();requests.push({kind,chain,network,address,subject});return subject;};const api={getSummary$:vi.fn(request('summary')),getHoldings$:vi.fn(request('holdings')),getActivity$:vi.fn(request('activity'))};TestBed.configureTestingModule({providers:[{provide:ActivatedRoute,useValue:{paramMap:params}},{provide:PortfolioV2ApiService,useValue:api},{provide:PortfolioSessionService,useValue:{valuesHidden:signal(false)}}]});TestBed.overrideComponent(EphemeralPortfolioComponent,{set:{template:'',imports:[]}});const view=TestBed.createComponent(EphemeralPortfolioComponent);view.detectChanges();return {view,component:view.componentInstance,params,requests,api};}
it('route network/address changes cancel old reads and clear visible evidence',()=>{const {component,params,requests}=fixture();requests.forEach(r=>{r.subject.next({address:'first'});r.subject.complete();});expect(component.summary()?.address).toBe('first');params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(component.summary()).toBeNull();expect(component.holdings()).toBeNull();expect(component.failure()).toBe('');expect(requests.slice(3).map(r=>r.network)).toEqual(['signet','signet','signet']);});
it('late old responses and responses after destroy cannot publish',()=>{const {component,params,requests,view}=fixture();params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(requests.slice(0,3).every(r=>!r.subject.observed)).toBe(true);requests.slice(0,3).forEach(r=>{r.subject.next({address:'first'});r.subject.complete();});expect(component.summary()).toBeNull();view.destroy();expect(requests.slice(3).every(r=>!r.subject.observed)).toBe(true);});
it('errors clear evidence and a later address remains retryable',()=>{const {component,params,requests}=fixture();requests[0].subject.error(Error('private detail'));expect(component.failure()).toContain('could not be read');expect(component.failure()).not.toContain('private detail');params.next(convertToParamMap({chain:'bitcoin',network:'signet',address:'second'}));expect(component.failure()).toBe('');requests.slice(3).forEach(r=>{r.subject.next({address:'second'});r.subject.complete();});expect(component.summary()?.address).toBe('second');});
