// @vitest-environment jsdom
import { describe,expect,it,vi } from 'vitest';
import { signal } from '@angular/core';
import { WorkspaceRedirectComponent } from './workspace-redirect.component';
function setup(){let migrated=false;const c=Object.create(WorkspaceRedirectComponent.prototype);c.pending=signal(false);c.previewSignal=signal({watched:[],watchedCount:0,labelCount:0,groupCount:0,contentHash:'displayed-preview'});c.errorSignal=signal('');c.store={isUnlocked:()=>true,migrated:()=>migrated,activePortfolio:()=>({id:'test-owned'}),migrateWorkspace:vi.fn()};c.router={navigate:vi.fn().mockResolvedValue(true)};return {c,setMigrated:()=>{migrated=true;}};}
describe('workspace migration consumer lifecycle',()=>{
 it('guards pending duplicate and persists displayed preview despite changed local storage',async()=>{const {c}=setup();let resolve!:()=>void;c.store.migrateWorkspace.mockReturnValue(new Promise<void>(r=>{resolve=r;}));const preview=c.previewSignal();const pending=c.run();expect(c.pending()).toBe(true);await c.run();c.skip();expect(c.store.migrateWorkspace).toHaveBeenCalledOnce();expect(c.router.navigate).not.toHaveBeenCalled();expect(c.store.migrateWorkspace).toHaveBeenCalledWith('Migrated watchlist',preview);resolve();await pending;expect(c.pending()).toBe(false);expect(c.router.navigate).toHaveBeenCalledWith(['/portfolio/p','test-owned','overview']);});
 it('retains migration preview on failure and allows explicit retry',async()=>{const {c}=setup();c.store.migrateWorkspace.mockRejectedValueOnce(Error('quota')).mockResolvedValueOnce(undefined);await c.run();expect(c.error()).toContain('old watchlist is retained');expect(c.pending()).toBe(false);expect(c.router.navigate).not.toHaveBeenCalled();await c.run();expect(c.error()).toBe('');expect(c.store.migrateWorkspace).toHaveBeenCalledTimes(2);});
 it('distinguishes saved migration with rejected or cancelled navigation and retries opening only',async()=>{for(const rejection of [false,Error('navigation')]){const {c,setMigrated}=setup();c.store.migrateWorkspace.mockImplementation(async()=>setMigrated());if(rejection instanceof Error)c.router.navigate.mockRejectedValueOnce(rejection);else c.router.navigate.mockResolvedValueOnce(false);await c.run();expect(c.error()).toContain('Migration is saved');expect(c.pending()).toBe(false);c.skip();await Promise.resolve();expect(c.store.migrateWorkspace).toHaveBeenCalledOnce();expect(c.router.navigate).toHaveBeenCalledTimes(2);}});
});
