import fs from 'fs'; import path from 'path'; import vm from 'vm'; import ts from 'typescript'; import {EventEmitter} from 'events';
function load(relative:string,deps:any,extra:any={}){const exports:any={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',relative),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,{exports,require:(id:string)=>deps[id]||{},setInterval,clearInterval,Error,...extra});return exports.default;}
class Missing extends Error{}
const identity={adminEnvelope:()=>({}),adminTimestamp:()=> '2026-09-15T00:00:00Z',explorerEnvironment:()=> 'test',explorerNetwork:()=> 'regtest',explorerRelease:()=>({backendSha:'abc',version:'1'})};
function setup(store:any={},extra:any={}){const handlers:any={};const app:any={use:()=>app,get:(url:string,fn:any)=>{handlers[url]=fn;return app;},post:()=>app};const source=load('api/admin-adapter/admin-adapter.routes.ts',{'crypto':{randomUUID:()=> 'id'},'@bitcoinuniverse/ecosystem-contracts/admin-control':{ADMIN_RESOURCE_KINDS:['run','release'],ADMIN_CONTROL_SUPPORTED_VERSIONS:[]},'../../config':{DATABASE:{ENABLED:true}},'../../logger':{info:()=>{},err:()=>{}},'./admin-adapter.security':{adminAdapterJsonParser:()=>{},adminAdapterGuard:()=>{}},'./admin-adapter.replay':{createAdminReplayStore:()=>({kind:'memory',claim:async()=>'claimed'})},'./admin-adapter.identity':identity,'./admin-adapter.runs':{__esModule:true,default:store,AdminRunNotFound:Missing},'../backend-info':{getBackendInfo:()=>({})},'../blocks':{getCurrentBlockHeight:()=>1},'../mempool':{getMempool:()=>({})},'./admin-adapter.snapshot':{buildExplorerSnapshot:async()=>({components:[],dependencies:[],indexers:[]})}},extra);source.initRoutes(app);return handlers;}
function response(){const r:any=new EventEmitter();r.statusCode=200;r.status=(n:number)=>{r.statusCode=n;return r;};r.json=(b:any)=>{r.body=b;return r;};r.setHeader=()=>{};r.flushHeaders=()=>{};r.end=jest.fn();r.write=jest.fn(()=>true);return r;}
const run={runId:'old',operationId:'verify',state:'SUCCEEDED',target:'node'};
test('resource lookup reads an exact run even outside latest200',async()=>{const store={get:jest.fn(async()=>run),list:jest.fn(async()=>[])};const r=response();await setup(store)['/internal/admin/v1/resources/:kind/:id']({params:{kind:'run',id:'old'}},r);expect(r.statusCode).toBe(200);expect(r.body.resource.id).toBe('old');expect(store.get).toHaveBeenCalledWith('old');expect(store.list).not.toHaveBeenCalled();});
test.each([{error:new Missing(),status:404},{error:Error('offline'),status:503}])('run resource absence differs from source failure $status',async({error,status})=>{const r=response();await setup({get:async()=>{throw error;},list:async()=>[]})['/internal/admin/v1/resources/:kind/:id']({params:{kind:'run',id:'old'}},r);expect(r.statusCode).toBe(status);});
test('release search respects query',async()=>{const r=response();await setup({list:async()=>[]})['/internal/admin/v1/resources']({query:{kind:'release',q:'no-match'}},r);expect(r.body.items).toEqual([]);});
test('slow stream closes at first backpressure and releases timer',()=>{let tick:any;const clear=jest.fn();const handler=setup({}, {setInterval:(fn:any)=>{tick=fn;return 1;},clearInterval:clear})['/internal/admin/v1/events'];const req=new EventEmitter(),r=response();r.write.mockReturnValue(false);handler(req,r);tick();tick();expect(r.write).toHaveBeenCalledTimes(1);expect(clear).toHaveBeenCalledTimes(1);expect(r.end).toHaveBeenCalledTimes(1);});
test('stream write error is contained and cleaned up',()=>{let tick:any;const clear=jest.fn();const handler=setup({}, {setInterval:(fn:any)=>{tick=fn;return 1;},clearInterval:clear})['/internal/admin/v1/events'];const r=response();r.write.mockImplementation(()=>{throw Error('closed');});handler(new EventEmitter(),r);expect(()=>tick()).not.toThrow();expect(clear).toHaveBeenCalledTimes(1);});
test('stream cap is bounded and disconnected clients release capacity',()=>{const clear=jest.fn();const handler=setup({}, {setInterval:()=>1,clearInterval:clear})['/internal/admin/v1/events'];const requests:EventEmitter[]=[];for(let i=0;i<32;i++){const request=new EventEmitter();requests.push(request);handler(request,response());}const refused=response();handler(new EventEmitter(),refused);expect(refused.statusCode).toBe(503);requests[0].emit('close');const next=response();const nextReq=new EventEmitter();handler(nextReq,next);expect(next.statusCode).toBe(200);requests.forEach(r=>r.emit('close'));nextReq.emit('close');expect(clear).toHaveBeenCalledTimes(33);});
test('response error releases stream timer and listeners',()=>{const clear=jest.fn();const handler=setup({}, {setInterval:()=>1,clearInterval:clear})['/internal/admin/v1/events'];const req=new EventEmitter(),r=response();handler(req,r);r.emit('error',Error('socket'));expect(clear).toHaveBeenCalledTimes(1);expect(req.listenerCount('close')).toBe(0);expect(r.listenerCount('close')).toBe(0);});
test('run searches are applied before bounded SQL limit with literal bound query',async()=>{const query=jest.fn(async(_sql:string,_params:any[])=>[[]]);const store=load('api/admin-adapter/admin-adapter.runs.ts',{'../../config':{DATABASE:{ENABLED:true}},'../../database':{query},'./admin-adapter.identity':identity});await store.list(Infinity," %_'needle ");expect(query.mock.calls[0][0]).toContain('WHERE LOCATE');expect(query.mock.calls[0][1]).toEqual(["%_'needle",50]);});
test('disabled run source does not masquerade as empty listing or audit',async()=>{const store=load('api/admin-adapter/admin-adapter.runs.ts',{'../../config':{DATABASE:{ENABLED:false}}});await expect(store.list()).rejects.toThrow('database');await expect(store.auditEntries()).rejects.toThrow('database');});

