import http from 'http';
import { gzipSync } from 'zlib';
const { JsonRPC } = require('../rpc-api/jsonrpc');
describe('RPC negotiated bounded gzip and status',()=>{
 async function serve(handler,run){const s=http.createServer(handler);await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const c=new JsonRPC({host:'127.0.0.1',port:(s.address() as any).port,timeout:500});try{await run(c)}finally{c.agent.destroy();s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()))}}
 function reply(q,r,transform=(b)=>b,encoding='gzip'){let body='';q.on('data',b=>body+=b);q.on('end',()=>{const call=JSON.parse(body);const v=Array.isArray(call)?call.map((c,i)=>({id:c.id,result:i})).reverse():{id:call.id,result:'é😀'};if(encoding)r.setHeader('Content-Encoding',encoding);r.end(transform(Buffer.from(JSON.stringify(v))))})}
 it('non-RPC503 is HTTP unavailable without reflecting content or retrying a write',async()=>{let count=0;await serve((_q,r)=>{count++;r.statusCode=503;r.end(JSON.stringify({error:'sensitive caller input'}))},async c=>{await expect(c.call('sendrawtransaction',['opaque'])).rejects.toMatchObject({code:'ERPC_HTTP',message:'RPC response status 503'});expect(count).toBe(1)})});
 it('authentication status never becomes a recognized object absence',async()=>{await serve((q,r)=>{let b='';q.on('data',x=>b+=x);q.on('end',()=>{r.statusCode=401;r.end(JSON.stringify({id:JSON.parse(b).id,error:{code:-5,message:'secret'}}))})},async c=>{await expect(c.call('getrawtransaction',[])).rejects.toMatchObject({code:'ERPC_HTTP'})})});
 it('wrong HTTP500 identity never accepts its RPC domain code',async()=>{await serve((_q,r)=>{r.statusCode=500;r.end(JSON.stringify({id:'wrong',error:{code:-5,message:'secret'}}))},async c=>{await expect(c.call('getblock',[])).rejects.toMatchObject({code:'ERPC_HTTP'})})});
 it('gzip preserves UTF8 and batch order and old identity/no-header responses still work',async()=>{await serve((q,r)=>{expect(q.headers['accept-encoding']).toBe('gzip');reply(q,r,gzipSync)},async c=>{await expect(c.call('echo',[])).resolves.toBe('é😀');await expect(c.call([{method:'a',params:[]},{method:'b',params:[]}])).resolves.toEqual([0,1])});await serve((q,r)=>reply(q,r,b=>b,''),async c=>{await expect(c.call('echo',[])).resolves.toBe('é😀')})});
 it('compressed HTTP500 preserves only matching valid Core domain code',async()=>{await serve((q,r)=>{let b='';q.on('data',x=>b+=x);q.on('end',()=>{r.statusCode=500;r.setHeader('Content-Encoding','gzip');r.end(gzipSync(Buffer.from(JSON.stringify({id:JSON.parse(b).id,result:null,error:{code:-5,message:'secret'}}))))})},async c=>{await expect(c.call('getblock',[])).rejects.toMatchObject({code:-5,message:'Block not found'})})});
 it('compressed wrong identity remains rejected',async()=>{await serve((_q,r)=>{r.setHeader('Content-Encoding','gzip');r.end(gzipSync(Buffer.from(JSON.stringify({id:'wrong',result:5}))))},async c=>{await expect(c.call('getblockcount',[])).rejects.toMatchObject({code:'ERPC_RESPONSE'})})});
 it('CRC corruption, truncation, trailing garbage and unsupported encodings fail without fallback',async()=>{for(const transform of [(b)=>{const z=gzipSync(b);z[z.length-8]^=1;return z},b=>gzipSync(b).subarray(0,-5),b=>Buffer.concat([gzipSync(b),Buffer.from('invalid')])])await serve((q,r)=>reply(q,r,transform),async c=>{await expect(c.call('echo',[])).rejects.toMatchObject({code:'ERPC_ENCODING'})});let count=0;await serve((q,r)=>{count++;reply(q,r,b=>b,'br')},async c=>{await expect(c.call('echo',[])).rejects.toMatchObject({code:'ERPC_ENCODING'});expect(count).toBe(1)})});
 it('wire cap and expansion cap reject separately including a gzip bomb',async()=>{await serve((q,r)=>reply(q,r,gzipSync),async c=>{c.opts.maxWireResponseBytes=10;await expect(c.call('echo',[])).rejects.toMatchObject({code:'ERPC_SIZE'})});await serve((q,r)=>{let body='';q.on('data',b=>body+=b);q.on('end',()=>{r.setHeader('Content-Encoding','gzip');r.end(gzipSync(Buffer.from(JSON.stringify({id:JSON.parse(body).id,result:'x'.repeat(1024*1024)}))))})},async c=>{c.opts.maxResponseBytes=1024;c.opts.maxWireResponseBytes=4096;await expect(c.call('echo',[])).rejects.toMatchObject({code:'ERPC_SIZE'})})});
 it('absolute timeout and abort cover compressed bodies and recover next call',async()=>{let first=true;await serve((q,r)=>{if(!first){reply(q,r,gzipSync);return}first=false;r.setHeader('Content-Encoding','gzip');r.write(gzipSync(Buffer.from('{')).subarray(0,5));const t=setInterval(()=>r.write(Buffer.from([0])),10);r.on('close',()=>clearInterval(t))},async c=>{c.opts.timeout=50;await expect(c.call('echo',[])).rejects.toMatchObject({code:'ETIMEDOUT'});c.opts.timeout=500;await expect(c.call('echo',[])).resolves.toBe('é😀')});await serve((_q,r)=>{r.setHeader('Content-Encoding','gzip');r.write(gzipSync(Buffer.from('{')).subarray(0,5))},async c=>{const a=new AbortController();setTimeout(()=>a.abort(),30);await expect(c.call('echo',[],{signal:a.signal})).rejects.toMatchObject({code:'EABORTED'})})});
});
