import { DefaultVtxo } from '@arkade-os/sdk';
import { Transaction } from '@scure/btc-signer';
import { decodeArkade } from './codec.mjs';
import fs from 'node:fs';
const pubkey='79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798';
const server='c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5';
const policy=new DefaultVtxo.Script({pubKey:Buffer.from(pubkey,'hex'),serverPubKey:Buffer.from(server,'hex'),csvTimelock:{type:'blocks',value:144n}});
const tx=new Transaction({version:3,allowUnknownOutputs:true});tx.addInput({txid:new Uint8Array(32).fill(1),index:0,witnessUtxo:{script:policy.pkScript,amount:1000n}});tx.addOutput({script:policy.pkScript,amount:1000n});
const pkg={nodes:[{txid:tx.id,tx:Buffer.from(tx.toPSBT()).toString('base64'),children:{}}],leaf_outpoint:tx.id+':0',default_vtxo:{pubkey,server_pubkey:server,exit_delay_blocks:144}};
const result=decodeArkade(pkg);fs.writeFileSync('../../../arkade-codec-fixture.json',JSON.stringify(pkg,null,2));console.log(JSON.stringify({engine:result.engine,transactions:result.transactions.length,finalized:result.finalized,id:result.vtxo_id}));
