import { describe,expect,it } from 'vitest';
import { appendSv2Page,configuredSv2Profile,validateSv2Page } from './stratum-v2.evidence';
import { configuredFixture,pagesFixture } from './stratum-v2.fixtures';
const copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
describe('SV2 observed source and captured page boundaries',()=>{
 it('accepts all three real-wire subsets and exact remaining-value strings',()=>{const c=configuredSv2Profile(configuredFixture);for(const f of ['roles','templates','declarations'] as const)expect(validateSv2Page(copy(pagesFixture[f]),c,f).items.length).toBeGreaterThan(0);const p=copy(pagesFixture.templates);p.items[0].coinbaseValueRemainingSats='18446744073709551615';expect(validateSv2Page(p,c,'templates').items[0].coinbaseValueRemainingSats).toBe('18446744073709551615');});
 it('rejects different source profile and mismatched native checkpoint header',()=>{const c=configuredSv2Profile(configuredFixture);const p=copy(pagesFixture.roles);p.source.profile.core.configurationSha256='f'.repeat(64);expect(()=>validateSv2Page(p,c,'roles')).toThrow('independent');const q=copy(pagesFixture.roles);q.source.core.checkpoint.blockHash='f'.repeat(64);expect(()=>validateSv2Page(q,c,'roles')).toThrow('header');});
 it('does not accept guessed total coinbase, tx arrays, or over-u64 atomic values',()=>{const c=configuredSv2Profile(configuredFixture);const p=copy(pagesFixture.templates);p.items[0].coinbaseTxValueSats='1' as any;expect(()=>validateSv2Page(p,c,'templates')).toThrow();const q=copy(pagesFixture.declarations);q.items[0].minerDeclaredTxids=[] as any;expect(()=>validateSv2Page(q,c,'declarations')).toThrow();p.items[0].coinbaseTxValueSats=null;p.items[0].coinbaseValueRemainingSats='18446744073709551616';expect(()=>validateSv2Page(p,c,'templates')).toThrow();});
 it('rejects empty continued pages, duplicated events and false whole-history closure',()=>{const c=configuredSv2Profile(configuredFixture),p=copy(pagesFixture.templates);p.items=[];p.nextCursor='next';expect(()=>validateSv2Page(p,c,'templates')).toThrow('progress');p.items=copy(pagesFixture.templates.items);p.items[1]=p.items[0];expect(()=>validateSv2Page(p,c,'templates')).toThrow();p.items=copy(pagesFixture.templates.items);p.completeHistory=true as any;expect(()=>validateSv2Page(p,c,'templates')).toThrow();});
 it('a retained cursor page cannot append overlaps or a changed snapshot/total',()=>{const p=copy(pagesFixture.templates),q=copy(p);p.items=p.items.slice(0,1);expect(()=>appendSv2Page(p,q,p.items,'templates')).toThrow('overlaps');q.items=q.items.slice(1);q.source.rawSnapshotSha256='e'.repeat(64);expect(()=>appendSv2Page(p,q,p.items,'templates')).toThrow('changed');});
});
