import { HttpErrorResponse } from '@angular/common/http';
import { of,Subject,throwError } from 'rxjs';
import { expect,it,vi } from 'vitest';
import { UniverseApiService } from '../universe-api.service';
import { configuredFixture,pagesFixture } from './stratum-v2.fixtures';
it('serializes exact independently selected regtest source/cursor and no-store without inferring Signet',()=>{const get=vi.fn(()=>of(pagesFixture.templates));const api=new UniverseApiService({get} as any,{isBrowser:true,network:'signet',env:{ROOT_NETWORK:'mainnet',SV2_SOURCE_PROFILE:configuredFixture}} as any,{} as any);let result:any;api.getStratumV2Page$('templates','opaque+cursor/x=').subscribe(v=>result=v);expect(get).toHaveBeenCalledWith('/signet/api/v1/stratum-v2/templates',{params:{network:'regtest',limit:'100',cursor:'opaque+cursor/x='},headers:{'Cache-Control':'no-store'}});expect(result.items).toHaveLength(2);});
it('missing independent profile performs no HTTP and invalid native response remains an error',()=>{const get=vi.fn(()=>of({...pagesFixture.roles,schemaVersion:'old'}));const state={isBrowser:true,network:'signet',env:{ROOT_NETWORK:'signet',SV2_SOURCE_PROFILE:null as any}};const api=new UniverseApiService({get} as any,state as any,{} as any);let error:any;api.getStratumV2Page$('roles').subscribe({error:e=>error=e});expect(error.message).toContain('configured');expect(get).not.toHaveBeenCalled();state.env.SV2_SOURCE_PROFILE=configuredFixture;api.getStratumV2Page$('roles').subscribe({error:e=>error=e});expect(error).toBeInstanceOf(Error);expect(get).toHaveBeenCalledTimes(1);});
it('source cursor conflict retains HTTP409 for explicit panel restart',()=>{const api=new UniverseApiService({get:()=>throwError(()=>new HttpErrorResponse({status:409}))} as any,{isBrowser:true,network:'',env:{SV2_SOURCE_PROFILE:configuredFixture}} as any,{} as any);let error:any;api.getStratumV2Page$('declarations','expired').subscribe({error:e=>error=e});expect(error.status).toBe(409);});
it('HTTP subscription cancellation releases the pending source read',()=>{const pending=new Subject<any>();const api=new UniverseApiService({get:()=>pending} as any,{isBrowser:true,network:'',env:{SV2_SOURCE_PROFILE:configuredFixture}} as any,{} as any);const read=api.getStratumV2Page$('roles').subscribe();expect(pending.observed).toBe(true);read.unsubscribe();expect(pending.observed).toBe(false);});
