// Test-owned contract observations, not native chain acceptance.
import { LiquidConfiguredPair, LiquidObservatoryCoverage } from './liquid-observatory.types';
export const pair: LiquidConfiguredPair={profile:{schema:'universe-liquid-pair-profile-v1',network:'elementsregtest',parentNetwork:'regtest',elementsGenesis:'1'.repeat(64),parentGenesis:'2'.repeat(64),policyAsset:'3'.repeat(64),elementsVersion:230304,parentVersion:300300,elementsSourceRevision:'4'.repeat(40),parentSourceRevision:'5'.repeat(40),epochLength:10,peginConfirmationDepth:2},profileSha256:'6'.repeat(64)};
export function coverage(processed=12):LiquidObservatoryCoverage{return {schemaVersion:'universe-liquid-observatory-v1',scope:'canonical-public-blocks-and-parent-peg-evidence',status:processed===12?'COMPLETE_AT_OBSERVED_PAIR':'PARTIAL',source:{...pair,observedAt:'2026-10-04T13:00:00Z',elements:{height:11,hash:'7'.repeat(64),genesis:pair.profile.elementsGenesis,parametersRoot:'8'.repeat(64),epochLength:10,epochAge:1},parent:{height:113,hash:'9'.repeat(64),genesis:pair.profile.parentGenesis},federation:{signblockScript:'51',fedpegScript:'51',fedpegProgram:'51'}},progress:{processedBlocks:processed,expectedBlocks:12,nextHeight:processed,pageLimit:16},cursor:{height:processed-1,blockHash:processed===0?null:processed===12?'7'.repeat(64):'a'.repeat(64)}};}
export function summary(){return {coverage:coverage(),blockHeight:11,blockHash:'7'.repeat(64),dynamicFederation:{currentEpoch:1,signersOnline:null,totalSigners:null,blockSigningThreshold:null,parametersRoot:'8'.repeat(64)},peggedReserveSats:null,activeAssetCount:null,confidentialTxPercentage:null,observedIssuanceCount:1,observedOutputCounts:{explicit:2,confidential:3,scope:'projected-public-outputs',amountsUnknown:true},recentPegs:[]};}
export function federation(){return {coverage:coverage(),epochNumber:1,signblockscript:'51',fedpegScript:'51',fedpegProgram:'51',parametersRoot:'8'.repeat(64),activeSigners:null,totalSigners:null,threshold:null,startHeight:10,endHeight:19,blockSignerCounts:null,parameterHistoryLimit:100,observedFullParameterRecordsTotal:0,observedFullParameterRecords:[]};}
export const publication={revision:'test-1',sha256:'b'.repeat(64),scope:'test-owned-publication'};
export function asset(){return {coverage:coverage(),publication,assetId:'c'.repeat(64),name:'Test-owned asset',ticker:'TEST',precision:8,issuanceTxid:'d'.repeat(64),issuanceVin:0,assetEntropy:'e'.repeat(64),reissuanceToken:null,provenance:'Test-owned display metadata',initialIssuanceAmountAtomic:'9007199254740993',initialIssuanceAmountCommitment:null,circulatingAmount:null,issuerPubkey:null,hasProof:true};}
export function assets(){return {coverage:coverage(),assets:[asset()],total:1,offset:0,limit:50,nextOffset:null,publication};}
export function pegs(){return {coverage:coverage(),pegs:[],total:0,offset:0,limit:50,nextOffset:null,pegOuts:{status:'OBSERVED_REQUESTS_ONLY',requests:[],total:0,nextOffset:null,parentPayoutStatus:'UNKNOWN',reason:'No parent payout authority.'}};}
