import { LiquidConfiguredPair, LiquidNetwork, LiquidObservatoryCoverage } from './liquid-observatory.types';
const hash = (v: unknown): v is string => typeof v === 'string' && /^[0-9a-f]{64}$/.test(v);
const integer = (v: unknown, max=Number.MAX_SAFE_INTEGER): v is number => Number.isSafeInteger(v) && Number(v)>=0 && Number(v)<=max;
const hex = (v: unknown): v is string => typeof v==='string' && /^(?:[0-9a-f]{2})*$/.test(v) && v.length<=20000;
const atomic = (v: unknown): v is string => typeof v==='string' && /^(?:0|[1-9][0-9]{0,19})$/.test(v) && BigInt(v)<=18446744073709551615n;
export function requireLiquid(ok: unknown, reason='The Liquid observation does not satisfy the selected public pair contract.'): asserts ok { if(!ok) throw new Error(reason); }
export function liquidProfile(configured: unknown, network: LiquidNetwork): LiquidConfiguredPair {
 if(typeof configured==='string') { requireLiquid(configured.length<=16384,'The public Liquid profile configuration exceeds its bounded size.'); try { configured=JSON.parse(configured); } catch { throw new Error('Invalid public Liquid source profiles.'); } }
 requireLiquid(configured && typeof configured==='object' && !Array.isArray(configured) && Object.keys(configured).length<=3 && Object.keys(configured).every(key=>['liquidv1','liquidtestnet','elementsregtest'].includes(key)),'Invalid public Liquid network profile map.');
 const pair=(configured as any)?.[network], p=pair?.profile;
 requireLiquid(pair && Object.keys(pair).sort().join(',')==='profile,profileSha256' && p && Object.keys(p).sort().join(',')==='elementsGenesis,elementsSourceRevision,elementsVersion,epochLength,network,parentGenesis,parentNetwork,parentSourceRevision,parentVersion,peginConfirmationDepth,policyAsset,schema','The public Liquid pair contains unsupported fields.');
 requireLiquid(p && p.schema==='universe-liquid-pair-profile-v1' && p.network===network && p.parentNetwork===({liquidv1:'main',liquidtestnet:'test',elementsregtest:'regtest'} as const)[network], 'No independently configured Liquid pair for this exact network.');
 requireLiquid(hash(pair.profileSha256) && hash(p.elementsGenesis) && hash(p.parentGenesis) && p.parentGenesis!==p.elementsGenesis && hash(p.policyAsset) && /^[0-9a-f]{40}$/.test(p.elementsSourceRevision) && /^[0-9a-f]{40}$/.test(p.parentSourceRevision) && integer(p.elementsVersion) && p.elementsVersion>0 && integer(p.parentVersion) && p.parentVersion>0 && integer(p.epochLength,100000) && p.epochLength>0 && integer(p.peginConfirmationDepth,100000) && p.peginConfirmationDepth>0,'Invalid independently configured Liquid pair.');
 return pair;
}
export function validateLiquidCoverage(value: unknown, expected: LiquidConfiguredPair): LiquidObservatoryCoverage {
 const c=value as any, s=c?.source, p=s?.profile;
 requireLiquid(c?.schemaVersion==='universe-liquid-observatory-v1' && c.scope==='best-chain-public-blocks-and-parent-peg-evidence' && ['PARTIAL','COMPLETE_AT_OBSERVED_PAIR'].includes(c.status));
 requireLiquid(s?.profileSha256===expected.profileSha256 && p && Object.keys(p).length===Object.keys(expected.profile).length && Object.keys(expected.profile).every(key=>p[key]===expected.profile[key as keyof typeof expected.profile]), 'The observed Liquid pair differs from the independently configured profile.');
 requireLiquid(s.elements?.genesis===p.elementsGenesis && s.parent?.genesis===p.parentGenesis && integer(s.elements.height) && integer(s.parent.height) && hash(s.elements.hash) && hash(s.parent.hash) && hash(s.elements.parametersRoot) && s.elements.epochLength===p.epochLength && integer(s.elements.epochAge,p.epochLength-1) && Number.isFinite(Date.parse(s.observedAt)) && hex(s.federation?.signblockScript) && hex(s.federation?.fedpegScript) && hex(s.federation?.fedpegProgram));
 const q=c.progress;
 requireLiquid(q && integer(q.processedBlocks,100000) && q.expectedBlocks===s.elements.height+1 && q.nextHeight===q.processedBlocks && q.pageLimit===16 && q.processedBlocks<=q.expectedBlocks && c.cursor?.height===q.processedBlocks-1 && (q.processedBlocks===0?c.cursor.blockHash===null:hash(c.cursor.blockHash)));
 requireLiquid((c.status==='COMPLETE_AT_OBSERVED_PAIR')===(q.processedBlocks===q.expectedBlocks) && (c.status!=='COMPLETE_AT_OBSERVED_PAIR'||c.cursor.blockHash===s.elements.hash));
 return c;
}
export function liquidPageFence(c: LiquidObservatoryCoverage): string { return JSON.stringify([c.source.profileSha256,c.source.elements.height,c.source.elements.hash,c.source.parent.height,c.source.parent.hash,c.cursor.height,c.cursor.blockHash]); }
export function exactLiquidAmount(v: string, precision=8): string { requireLiquid(atomic(v) && integer(precision,18)); const digits=v.padStart(precision+1,'0'); return precision?digits.slice(0,-precision)+'.'+digits.slice(-precision):digits; }
export function validateLiquidRead<T>(data: T, kind: string, expected: LiquidConfiguredPair, offset=0, limit=50): T {
 const v=data as any, c=validateLiquidCoverage(kind==='projection'?v:v?.coverage,expected);
 if(kind==='summary') {
  requireLiquid(v.blockHeight===c.source.elements.height && v.blockHash===c.source.elements.hash && v.peggedReserveSats===null && v.activeAssetCount===null && v.confidentialTxPercentage===null && integer(v.observedIssuanceCount));
  requireLiquid(v.dynamicFederation?.currentEpoch===Math.floor(v.blockHeight/expected.profile.epochLength) && v.dynamicFederation.signersOnline===null && v.dynamicFederation.totalSigners===null && v.dynamicFederation.blockSigningThreshold===null && v.dynamicFederation.parametersRoot===c.source.elements.parametersRoot && integer(v.observedOutputCounts?.confidential) && integer(v.observedOutputCounts?.explicit) && v.observedOutputCounts.scope==='projected-public-outputs' && v.observedOutputCounts.amountsUnknown===true);
 }
 const publication=(x:any)=>requireLiquid(x && typeof x.revision==='string' && x.revision.length>0 && x.revision.length<=128 && hash(x.sha256) && typeof x.scope==='string' && x.scope.length>0 && x.scope.length<=1024);
 const asset=(a:any)=>{requireLiquid(a && hash(a.assetId) && hash(a.issuanceTxid) && hash(a.assetEntropy) && integer(a.issuanceVin) && integer(a.precision,8) && typeof a.name==='string' && typeof a.ticker==='string' && typeof a.provenance==='string' && (a.reissuanceToken===null||hash(a.reissuanceToken)) && a.circulatingAmount===null && a.issuerPubkey===null && a.hasProof===true); requireLiquid((a.initialIssuanceAmountAtomic===null && typeof a.initialIssuanceAmountCommitment==='string' && /^[0-9a-f]{66}$/.test(a.initialIssuanceAmountCommitment)) || (atomic(a.initialIssuanceAmountAtomic) && a.initialIssuanceAmountCommitment===null)); publication(a.publication);validateLiquidCoverage(a.coverage,expected);requireLiquid(liquidPageFence(a.coverage)===liquidPageFence(c));};
 const page=(rows:any,total:any,next:any)=>{requireLiquid(Array.isArray(rows) && rows.length<=limit && integer(total,100000) && v.offset===offset && v.limit===limit && rows.length===Math.max(0,Math.min(limit,total-offset)) && next===(offset+rows.length<total?offset+rows.length:null) && (next===null||rows.length>0));};
 if(kind==='assets'){ publication(v.publication);page(v.assets,v.total,v.nextOffset);v.assets.forEach(asset);requireLiquid(new Set(v.assets.map((a:any)=>a.assetId)).size===v.assets.length && v.assets.every((a:any)=>a.publication.sha256===v.publication.sha256 && a.publication.revision===v.publication.revision)); }
 if(kind==='asset')asset(v);
 if(kind==='pegs') {
  page(v.pegs,v.total,v.nextOffset);
  v.pegs.forEach((a:any)=>requireLiquid(a.type==='peg-in' && a.status==='confirmed' && hash(a.txid) && a.liquidTxid===a.txid && integer(a.vin) && a.liquidVin===a.vin && a.id===a.txid+':'+a.vin && hash(a.parentTxid) && integer(a.parentVout) && atomic(a.amountAtomic) && a.amountSats===a.amountAtomic && hash(a.parentBlockHash) && integer(a.parentBlockHeight) && integer(a.parentConfirmations) && a.parentConfirmations>=expected.profile.peginConfirmationDepth && hash(a.parentProofSha256) && hex(a.parentOutputScript) && hex(a.claimScript) && hash(a.liquidBlockHash) && integer(a.liquidBlockHeight) && a.liquidBlockHeight<=c.cursor.height && a.confirmations===c.source.elements.height-a.liquidBlockHeight+1 && integer(a.timestamp)));
  const out=v.pegOuts;requireLiquid(out?.status==='OBSERVED_REQUESTS_ONLY' && out.parentPayoutStatus==='UNKNOWN' && typeof out.reason==='string');page(out.requests,out.total,out.nextOffset);
  out.requests.forEach((a:any)=>requireLiquid(a.type==='peg-out' && a.status==='request-confirmed' && a.parentPayoutStatus==='UNKNOWN' && a.bitcoinTxid===null && hash(a.txid) && integer(a.vout) && a.id===a.txid+':'+a.vout && a.parentGenesis===expected.profile.parentGenesis && hex(a.parentScript) && (a.parentAddress===null||typeof a.parentAddress==='string') && a.asset===expected.profile.policyAsset && atomic(a.amountAtomic) && hash(a.liquidBlockHash) && integer(a.liquidBlockHeight) && a.liquidBlockHeight<=c.cursor.height && a.confirmations===c.source.elements.height-a.liquidBlockHeight+1 && integer(a.timestamp)));
  requireLiquid(new Set(v.pegs.map((a:any)=>a.id)).size===v.pegs.length && new Set(out.requests.map((a:any)=>a.id)).size===out.requests.length);
 }
 if(kind==='federation'){requireLiquid(v.parametersRoot===c.source.elements.parametersRoot && v.signblockscript===c.source.federation.signblockScript && v.fedpegScript===c.source.federation.fedpegScript && v.fedpegProgram===c.source.federation.fedpegProgram && v.epochNumber===Math.floor(c.source.elements.height/expected.profile.epochLength) && v.startHeight===v.epochNumber*expected.profile.epochLength && v.endHeight===v.startHeight+expected.profile.epochLength-1 && v.activeSigners===null && v.totalSigners===null && v.threshold===null && v.blockSignerCounts===null && v.parameterHistoryLimit===100 && integer(v.observedFullParameterRecordsTotal,100000) && Array.isArray(v.observedFullParameterRecords) && v.observedFullParameterRecords.length===Math.min(100,v.observedFullParameterRecordsTotal));v.observedFullParameterRecords.forEach((a:any)=>requireLiquid(integer(a.height) && a.height<=c.cursor.height && hash(a.blockHash) && hash(a.parametersRoot) && hex(a.signblockScript)));}
 return data;
}
