import { describe, expect, it, vi } from 'vitest';
import { of } from 'rxjs';
import { UniverseApiService } from '../universe-api.service';
import { exactLiquidAmount,liquidProfile,validateLiquidCoverage,validateLiquidRead } from './liquid-evidence';
import { pair,coverage,summary,assets,pegs } from './liquid-fixtures';
function client(reply:any,configured:any={elementsregtest:pair}){const get=vi.fn(()=>of(reply)),post=vi.fn(()=>of(reply));return {get,post,api:new UniverseApiService({get,post} as any,{isBrowser:true,network:'signet',env:{LIQUID_SOURCE_PROFILES:configured}} as any,{} as any)};}
describe('Liquid independent pair and exact public evidence',()=>{
 it('keeps u64 atomic values exact without Number rounding',()=>{expect(exactLiquidAmount('9007199254740993')).toBe('90071992.54740993');expect(exactLiquidAmount('18446744073709551615')).toBe('184467440737.09551615');expect(()=>exactLiquidAmount('18446744073709551616')).toThrow();});
 it('fails closed without profile and rejects a BitcoinSignet parent inference',()=>{expect(()=>liquidProfile({},'elementsregtest')).toThrow();expect(()=>liquidProfile({elementsregtest:{...pair,profile:{...pair.profile,parentNetwork:'test'}}},'elementsregtest')).toThrow();});
 it.each(['elementsGenesis','parentGenesis','elementsSourceRevision','parentSourceRevision','elementsVersion','parentVersion','policyAsset'])('rejects wrong independently bound %s',key=>{const c=structuredClone(coverage());(c.source.profile as any)[key]=typeof (pair.profile as any)[key]==='number'?1:'0'.repeat((pair.profile as any)[key].length);expect(()=>validateLiquidCoverage(c,pair)).toThrow();});
 it('rejects false complete and inconsistent cursor, accepts the initial empty partial prefix',()=>{expect(validateLiquidCoverage(coverage(0),pair).cursor.height).toBe(-1);const c=coverage(4);c.status='COMPLETE_AT_OBSERVED_PAIR';expect(()=>validateLiquidCoverage(c,pair)).toThrow();const d=coverage();d.cursor.blockHash='f'.repeat(64);expect(()=>validateLiquidCoverage(d,pair)).toThrow();});
 it('retains unknown summary facts but rejects fabricated reserve or signer count',()=>{expect(validateLiquidRead(summary(),'summary',pair)).toBeTruthy();for(const key of ['peggedReserveSats','activeAssetCount','confidentialTxPercentage']){expect(()=>validateLiquidRead({...summary(),[key]:0},'summary',pair)).toThrow();}expect(()=>validateLiquidRead({...summary(),dynamicFederation:{...summary().dynamicFederation,signersOnline:0}},'summary',pair)).toThrow();});
 it('distinguishes opaque issuance from exact initial amount and rejects missing continuation progress',()=>{const p=assets();p.assets[0].initialIssuanceAmountAtomic=null;p.assets[0].initialIssuanceAmountCommitment='08'+'a'.repeat(64);expect(validateLiquidRead(p,'assets',pair)).toBe(p);p.assets[0].initialIssuanceAmountAtomic='1';expect(()=>validateLiquidRead(p,'assets',pair)).toThrow();expect(()=>validateLiquidRead({...assets(),assets:[],total:1,nextOffset:0},'assets',pair)).toThrow();});
 it('accepts a native-style public peg claim timestamp and exact protected amount',()=>{const p:any=pegs();p.total=1;p.pegs=[{txid:'c'.repeat(64),liquidTxid:'c'.repeat(64),vin:0,liquidVin:0,id:'c'.repeat(64)+':0',type:'peg-in',status:'confirmed',parentTxid:'d'.repeat(64),parentVout:0,amountAtomic:'9007199254740993',amountSats:'9007199254740993',parentBlockHash:'e'.repeat(64),parentBlockHeight:111,parentConfirmations:3,parentProofSha256:'f'.repeat(64),parentOutputScript:'51',claimScript:'51',liquidBlockHash:'7'.repeat(64),liquidBlockHeight:11,confirmations:1,timestamp:1791118800}];expect(validateLiquidRead(p,'pegs',pair)).toBe(p);p.pegs[0].amountSats='9007199254740992';expect(()=>validateLiquidRead(p,'pegs',pair)).toThrow();});
 it('permits independent peg-out offsets beyond a shorter peg-in list and never accepts a payout claim',()=>{const p:any=pegs();p.offset=50;expect(validateLiquidRead(p,'pegs',pair,50)).toBe(p);p.pegOuts.parentPayoutStatus='CONFIRMED';expect(()=>validateLiquidRead(p,'pegs',pair,50)).toThrow();});
 it('serializes exact network/page/no-store and checks the response before delivery',()=>{const f=client(assets());let accepted:any;f.api.getLiquidAssets$('elementsregtest').subscribe(v=>accepted=v);expect(accepted.assets[0].assetId).toBe(assets().assets[0].assetId);expect(f.get.mock.calls[0][0]).toContain('/api/v1/liquid/observatory/assets?network=elementsregtest&offset=0&limit=50');expect(f.get.mock.calls[0][1].headers).toEqual({'Cache-Control':'no-store'});const blocked=client(summary(),{});let error:any;blocked.api.getLiquidObservatorySummary$('elementsregtest').subscribe({error:e=>error=e});expect(error).toBeTruthy();expect(blocked.get).not.toHaveBeenCalled();});
 it('rejects malformed public profile size/extra fields and foreign observed genesis',()=>{expect(()=>liquidProfile({elementsregtest:{...pair,credential:'not-a-profile-field'}},'elementsregtest')).toThrow();expect(()=>liquidProfile(' '.repeat(16385),'elementsregtest')).toThrow();const c=coverage();c.source.parent.genesis='0'.repeat(64);expect(()=>validateLiquidCoverage(c,pair)).toThrow();});
 it('keeps the independent node checkpoint scoped and rejects wrong-network/false known reserves',()=>{const node={network:'elementsregtest',blockHeight:11,blockHash:'7'.repeat(64),initialBlockDownload:false,source:'owned-elements-rpc',scope:'checkpoint-and-policy-only',signblockScript:'51',fedpegScript:'51',fedpegProgram:'51',reserveSats:null,activeAssetCount:null,signersOnline:null};const f=client(node);let result:any;f.api.getLiquidNode$('elementsregtest').subscribe(v=>result=v);expect(result).toBe(node);for(const invalid of [{...node,network:'liquidv1'},{...node,reserveSats:'0'}]){let error:any;client(invalid).api.getLiquidNode$('elementsregtest').subscribe({error:e=>error=e});expect(error).toBeTruthy();}});
 it('posts only exact shared cursor and rejects invalid input before any HTTP',()=>{const f=client(coverage());f.api.advanceLiquidProjection$('elementsregtest',{height:-1,blockHash:null}).subscribe();expect(f.post.mock.calls[0][1]).toEqual({height:-1,blockHash:null});f.api.advanceLiquidProjection$('elementsregtest',{height:1,blockHash:null}).subscribe({error:()=>{}});expect(f.post).toHaveBeenCalledTimes(1);});
});
