// Public closed-program fixture generated by tools/simplicity-proof-checker/generate-fixtures.mjs
export const FORMAL_PROOF_SAMPLE = {
  "schema_version": "1.0.0",
  "proof_system": "simplicity-closed-program-v1",
  "source_text": "fn main() { assert!(jet::eq_32(42,42)); }",
  "program_bytes_hex": "d89b20000002a0408cdb882300813420e050",
  "program_cmr": "30b9ef28f62fbea32fe937efe2e13302b77bb036a4934b3547fe6bcba2721bd0",
  "source_hash": "bee51b83bf9db775a928abfc3e270fd73529e40a9529e70a1b875c587d2ecf9b",
  "compiler_revision": "simplicityhl-0.2.0",
  "libSimplicity_revision": "simplicity-sys-0.5.0",
  "proof_source": "{\"claim\":\"closed-program-succeeds\",\"program_cmr\":\"30b9ef28f62fbea32fe937efe2e13302b77bb036a4934b3547fe6bcba2721bd0\",\"program_bytes_sha256\":\"e979d6eeb2a74a1fd44493658d15550b5838e2ee9cabc645606cb267f769d87d\"}",
  "proof_source_hash": "250010694feb681af3492f7d7e7e21fe2d886bc68ccd12753cd2fdacaa8b8119",
  "proof_artifact_hash": "e979d6eeb2a74a1fd44493658d15550b5838e2ee9cabc645606cb267f769d87d",
  "statement": "The closed program evaluates successfully with no witness and no transaction environment.",
  "dependencies": [
    "simplicityhl-0.2.0",
    "simplicity-sys-0.5.0"
  ],
  "verification_command": ""
};
