import {describe,it,expect} from 'vitest';
import {inspectCashu,inspectFedimint} from './ecash-inspection';
import {ECASH_REFERENCE as samples} from './ecash-reference-fixtures';
import {base64urlnopad,bech32m} from '@scure/base';
function cashu(v:any){return 'cashuA'+base64urlnopad.encode(new TextEncoder().encode(JSON.stringify(v)));}
describe('actual offline ecash encodings',()=>{
 it('decodes official NUT00 V3 and V4 examples, preserving exact totals',()=>{expect(inspectCashu(samples.cashu_v3)).toMatchObject({version:'V3',total_amount:'10',proofs_count:2,unit:'sat',mints:['https://8333.space:3338/']});expect(inspectCashu(samples.cashu_v4)).toMatchObject({version:'V4',total_amount:'4',proofs_count:3,unit:'sat',mints:['http://localhost:3338/']});});
 it('decodes native Fedimint test vector with its exact federation and peer',()=>{expect(inspectFedimint(samples.fedimint)).toMatchObject({federation_id:'bea7ff4116f2b1d324c7b5d699cce4ac7408cee41db2c88027e21b76fff3b9f4',peers_count:1,endpoints:['wss://fedimintd.mplsfed.foo/']});});
 it('rejects fake prefix, invented empty token, wrong format, altered checksum and trailing bytes',()=>{for(const v of ['fed11garbage',samples.fedimint.slice(0,-1)+'q'])expect(()=>inspectFedimint(v)).toThrow();for(const v of [cashu({}),'cashuB'+samples.cashu_v3.slice(6),samples.cashu_v4+'A'])expect(()=>inspectCashu(v)).toThrow();const d=bech32m.decode(samples.fedimint as any,65536);const bytes=bech32m.fromWords(d.words);expect(()=>inspectFedimint(bech32m.encode('fed1',bech32m.toWords(Uint8Array.from([...bytes,0])),65536))).toThrow();});
 it('rejects unsafe quantities and invalid curve points without returning proof secrets',()=>{const parsed=JSON.parse(new TextDecoder().decode(base64urlnopad.decode(samples.cashu_v3.slice(6))));parsed.token[0].proofs[0].amount=Number.MAX_SAFE_INTEGER+1;expect(()=>inspectCashu(cashu(parsed))).toThrow();parsed.token[0].proofs[0].amount=1;parsed.token[0].proofs[0].C='02'+'ff'.repeat(32);expect(()=>inspectCashu(cashu(parsed))).toThrow();const result=JSON.stringify(inspectCashu(samples.cashu_v3));for(const p of parsed.token[0].proofs)expect(result.includes(p.secret)).toBe(false);});
});
import {EcashInspectComponent} from './ecash-inspect.component';
import {vi} from 'vitest';
it('component clears stale results and makes no network calls for official samples',()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);try{const c=new EcashInspectComponent({markForCheck:vi.fn()} as any);c.loadDemoCashu();expect(c.cashuResult?.total_amount).toBe('10');c.rawInput='fed11garbage';c.clear();expect(c.cashuResult).toBeNull();c.inspect();expect(c.fedimintResult).toBeNull();expect(c.errorMessage).toContain('Malformed');c.loadDemoFedimint();expect(c.fedimintResult?.peers_count).toBe(1);c.ngOnDestroy();expect(c.rawInput).toBe('');expect(c.fedimintResult).toBeNull();expect(fetch).not.toHaveBeenCalled();}finally{vi.unstubAllGlobals();}});
it('redacts optional native API secret while preserving peer count',()=>{const d=bech32m.decode(samples.fedimint as any,65536);const bytes=bech32m.fromWords(d.words);const secret=new TextEncoder().encode('public-test-secret');const extended=Uint8Array.from([3,...bytes.slice(1),2,secret.length+1,secret.length,...secret]);const result=inspectFedimint(bech32m.encode('fed1',bech32m.toWords(extended),65536));expect(result.api_secret_present).toBe(true);expect(result.peers_count).toBe(1);expect(JSON.stringify(result)).not.toContain('public-test-secret');});
it('rejects duplicate CBOR fields and oversized inputs; tolerates specified base64 padding',()=>{const duplicate=Uint8Array.from([0xa2,0x61,0x6d,0x61,0x61,0x61,0x6d,0x61,0x62]);expect(()=>inspectCashu('cashuB'+base64urlnopad.encode(duplicate))).toThrow();expect(()=>inspectFedimint('fed11'+'q'.repeat(65536))).toThrow();const pad=(4-samples.cashu_v4.slice(6).length%4)%4;expect(inspectCashu(samples.cashu_v4+'='.repeat(pad)).total_amount).toBe('4');});
