import {Component,OnDestroy,ChangeDetectionStrategy,ChangeDetectorRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterModule} from '@angular/router';
import {FormsModule} from '@angular/forms';
import {RelativeUrlPipe} from '@app/shared/pipes/relative-url/relative-url.pipe';
import {inspectCashu,inspectFedimint,CashuInspection,FedimintInspection} from './ecash-inspection';
import {ECASH_REFERENCE} from './ecash-reference-fixtures';
@Component({selector:'app-ecash-inspect',standalone:true,imports:[RelativeUrlPipe,CommonModule,RouterModule,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="intelligence-page container-xl">
 <header class="page-header mb-4"><div class="d-flex align-items-center gap-2 flex-wrap"><h1 class="mb-0">Ecash Inspector</h1><span class="badge bg-secondary">Local only</span></div><p class="text-muted mb-3">Decode a Cashu token or Fedimint invite without sending it anywhere.</p>
 <nav class="nav nav-pills gap-2"><a class="nav-link" [routerLink]="'/ecash'|relativeUrl">Overview</a><a class="nav-link" [routerLink]="'/ecash/cashu'|relativeUrl">Cashu Mints</a><a class="nav-link" [routerLink]="'/ecash/fedimint'|relativeUrl">Fedimint Federations</a><a class="nav-link active" [routerLink]="'/ecash/inspect'|relativeUrl">Offline Token Inspector</a></nav></header>
 <section class="card p-4 mb-4"><h2 class="h4">Inspect a token or invite</h2><form (ngSubmit)="inspect()"><label class="form-label" for="rawTokenInput">Cashu token or Fedimint invite</label><textarea id="rawTokenInput" class="form-control font-monospace" rows="4" name="rawInput" [(ngModel)]="rawInput" (ngModelChange)="clear()" autocomplete="off" spellcheck="false" maxlength="65536" aria-describedby="rawTokenHelp"></textarea><div id="rawTokenHelp" class="form-text">Up to 64 KiB. Tokens and invites stay in this browser.</div><div class="d-flex flex-wrap gap-2 mt-3"><button type="submit" class="btn btn-primary" [disabled]="!rawInput.trim()">Inspect</button><button type="button" class="btn btn-outline-secondary" (click)="reset()">Clear</button><details class="ms-sm-2 align-self-center"><summary class="small text-muted">Load a public example</summary><div class="d-flex flex-wrap gap-2 mt-2"><button type="button" class="btn btn-sm btn-outline-secondary" (click)="loadDemoCashu()">Cashu V3</button><button type="button" class="btn btn-sm btn-outline-secondary" (click)="loadDemoCashuV4()">Cashu V4</button><button type="button" class="btn btn-sm btn-outline-secondary" (click)="loadDemoFedimint()">Fedimint</button></div></details></div></form><p *ngIf="sample" class="form-text mt-2 mb-0">Public example; it does not establish funds or federation identity.</p></section>
 <p *ngIf="errorMessage" role="alert" class="alert alert-danger">{{errorMessage}}</p>
 <section *ngIf="cashuResult as result" class="card p-4"><div class="d-flex justify-content-between gap-2 flex-wrap"><h2 class="h4 mb-0">Cashu token</h2><span class="badge bg-secondary">Structure decoded</span></div><p class="mt-3 mb-2"><strong>{{result.total_amount}} {{result.unit}}</strong> declared across {{result.proofs_count}} proofs · {{result.version}} / NUT-00</p><h3 class="h6 mt-3">Mint endpoints</h3><code *ngFor="let mint of result.mints" class="d-block text-break">{{mint}}</code><h3 class="h6 mt-3">Keysets</h3><code *ngFor="let id of result.keysets" class="d-block text-break">{{id}}</code><p class="small text-muted mt-3 mb-0">This checks encoding only. It does not verify mint signatures, proof validity, keysets, or spendable balance. Secrets and endpoint credentials are hidden.</p></section>
 <section *ngIf="fedimintResult as result" class="card p-4"><div class="d-flex justify-content-between gap-2 flex-wrap"><h2 class="h4 mb-0">Fedimint invite</h2><span class="badge bg-secondary">Structure decoded</span></div><p class="mt-3 mb-2">Federation ID <code class="text-break">{{result.federation_id}}</code></p><p class="mb-2">{{result.peers_count}} endpoint{{result.peers_count === 1 ? '' : 's'}} included</p><code *ngFor="let endpoint of result.endpoints" class="d-block text-break">{{endpoint}}</code><p class="small text-muted mt-3 mb-0">API secret: {{result.api_secret_present?'present and hidden':'not present'}} · {{result.unknown_fields}} unknown fields. No federation was contacted or authenticated.</p></section>
</div>`})
export class EcashInspectComponent implements OnDestroy {
 rawInput='';sample=false;errorMessage:string|null=null;cashuResult:CashuInspection|null=null;fedimintResult:FedimintInspection|null=null;private destroyed=false;
 constructor(private cd:ChangeDetectorRef){}
 clear():void{this.sample=false;this.errorMessage=null;this.cashuResult=null;this.fedimintResult=null;}
 reset():void{this.clear();this.rawInput='';this.cd.markForCheck();}
 ngOnDestroy():void{this.destroyed=true;this.clear();this.rawInput='';}
 private example(input:string):void{this.rawInput=input;this.inspect();this.sample=true;}
 loadDemoCashu():void{this.example(ECASH_REFERENCE.cashu_v3);}
 loadDemoCashuV4():void{this.example(ECASH_REFERENCE.cashu_v4);}
 loadDemoFedimint():void{this.example(ECASH_REFERENCE.fedimint);}
 inspect():void{if(this.destroyed)return;this.clear();const input=this.rawInput.trim();if(!input)return;try{if(input.startsWith('cashu'))this.cashuResult=inspectCashu(input);else if(/^fed11|^fedimint/i.test(input))this.fedimintResult=inspectFedimint(input);else throw Error();}catch{this.errorMessage='Malformed or unsupported token/invite. No validity or balance established. Supported: Cashu A JSON, Cashu B definite-length CBOR, Fedimint fed11 and fedimint consensus encodings.';}this.cd.markForCheck();}
}
