import { describe,expect,it } from 'vitest';
import { checkedUtxoEvidence } from './utxo-evidence';
const h='ab'.repeat(32),m='cd'.repeat(32),at='2026-10-05T00:00:00.000Z';
const stats={network:'signet',block_height:1,block_hash:h,total_utxos:1,total_amount_sats:1,muhash:m,bogo_size:'90',observed_at_utc:at,block_time:1791158400};
const fixtures:Record<string,any>={
 '/api/v1/intelligence/utxo/overview':{...stats,dormant_10yr_sats:null,uneconomical_at_10_sat_vb_sats:null,last_reconciled_utc:null,reconciled:false,projection_configured:false,scope:'Controlled node observation.',source:{method:'owned Core coinstatsindex',observed_at_utc:at,freshness_limit_ms:30000}},
 '/api/v1/intelligence/utxo/reconciliation':{...stats,reconciled:false,projection_available:false,projection_muhash:null,hash_serialized_2:null,reorg_safe_checkpoint_height:null,scope:'Projection unavailable.'},
 '/api/v1/intelligence/utxo/cohorts':{block_height:1,block_hash:h,reconciled:true,scope:'Controlled complete partition.',script_types:[{script_type:'p2tr',utxo_count:1,total_sats:1,percent_of_supply:100}],age_cohorts:[{age_band:'<1 day',utxo_count:1,total_sats:1,percent_of_supply:100}],value_cohorts:[{value_band:'<10k sats',utxo_count:1,total_sats:1,percent_of_supply:100}]},
 '/api/v1/intelligence/utxo/economic-thresholds':{thresholds:[1,5,10,20,50,100].map(rate=>({feerate_sats_vb:rate,uneconomical_utxo_count:1,uneconomical_sats:1,unknown_spend_cost_utxo_count:0,percent_of_utxos:100,percent_of_supply:100,scope:'Input-only modeled cost.'})),count:6},
 '/api/v1/intelligence/utxo/spend-transitions':{transitions:[{height:1,block_hash:h,created_count:1,created_sats:1,spent_count:0,spent_sats:0,net_utxo_change:1,coin_days_destroyed:0,coin_age_destroyed_sat_seconds:'0',scope:'Controlled projected outputs.'}],count:1},
 '/api/v1/utxo-set/checkpoints':{checkpoints:[{blockHeight:1,blockHash:h,muhashHex:m,totalTxOuts:1,bogoSize:'90',totalAmountSats:'1',verifiedAtTimestamp:1791158400}],total:1},
 '/api/v1/utxo-set/distribution':{valueCohorts:[{label:'<10k sats',txOutCount:1,totalAmountSats:'1',supplyPercentage:'100'}],scriptTypes:[{scriptType:'p2tr',count:1,totalAmountSats:'1',percentage:'100'}]},
 // These are DTO-shape checks only. Both actual producer integrations are503.
 '/api/v1/utxo-set/protocols':{ordinalsBearingCount:0,runesBearingCount:0,stampsBearingCount:0,multiProtocolCount:0,pureBitcoinCount:1},
 '/api/v1/utreexo/roots':{blockHeight:1,numLeaves:1,roots:[h],forestRows:1},
};
describe('Current UTXO wire shapes, controlled fixtures only',()=>{
 it.each(Object.keys(fixtures))('retains actual units and discloses absent binding: %s',path=>{const value=structuredClone(fixtures[path]);const result=checkedUtxoEvidence(path,value,'signet');expect(result.value).toBe(value);if(['overview','reconciliation'].includes(path.split('/').at(-1)!))expect(result.disclosure).toBeNull();else expect(result.disclosure).toContain('no selected-network source binding');});
 it.each(Object.keys(fixtures))('rejects explicit foreign network on every response: %s',path=>expect(()=>checkedUtxoEvidence(path,{...fixtures[path],network:'mainnet'},'signet')).toThrow());
 it('rejects false reconciliation from mismatched measured commitments/counts',()=>{const value={...stats,reconciled:true,projection_available:true,projection_muhash:h,projection_total_utxos:1,projection_total_amount_sats:1,projection_height:1,rollback_floor_height:0,persistence:'atomic-checkpoint',reconciled_at_utc:at,hash_serialized_2:null,reorg_safe_checkpoint_height:null,scope:'Controlled reconciliation.'};expect(()=>checkedUtxoEvidence('/api/v1/intelligence/utxo/reconciliation',value,'signet')).toThrow();value.projection_muhash=m;expect(checkedUtxoEvidence('/api/v1/intelligence/utxo/reconciliation',value,'signet').value).toBe(value);});
 it('rejects incomplete cohort partitions and wrapper count mismatches',()=>{const cohort=structuredClone(fixtures['/api/v1/intelligence/utxo/cohorts']);cohort.age_cohorts[0].total_sats=2;expect(()=>checkedUtxoEvidence('/api/v1/intelligence/utxo/cohorts',cohort,'signet')).toThrow();for(const path of ['/api/v1/intelligence/utxo/economic-thresholds','/api/v1/intelligence/utxo/spend-transitions'])expect(()=>checkedUtxoEvidence(path,{...fixtures[path],count:2},'signet')).toThrow();});
 it('accepts producer scientific percentages without converting atomic strings',()=>{const value=structuredClone(fixtures['/api/v1/utxo-set/distribution']);value.valueCohorts[0].supplyPercentage='4.761904761904762e-14';value.scriptTypes[0].percentage='4.761904761904762e-14';value.valueCohorts.push({label:'large',txOutCount:1,totalAmountSats:'2099999999999999',supplyPercentage:'99.99999999999996'});value.scriptTypes.push({scriptType:'p2wpkh',count:1,totalAmountSats:'2099999999999999',percentage:'99.99999999999996'});expect(checkedUtxoEvidence('/api/v1/utxo-set/distribution',value,'signet').value).toBe(value);});
 it('rejects fabricated shares and nonzero amount attached to zero created outputs',()=>{const cohort=structuredClone(fixtures['/api/v1/intelligence/utxo/cohorts']);cohort.script_types[0].percent_of_supply=50;expect(()=>checkedUtxoEvidence('/api/v1/intelligence/utxo/cohorts',cohort,'signet')).toThrow();const transition=structuredClone(fixtures['/api/v1/intelligence/utxo/spend-transitions']);Object.assign(transition.transitions[0],{created_count:0,net_utxo_change:0});expect(()=>checkedUtxoEvidence('/api/v1/intelligence/utxo/spend-transitions',transition,'signet')).toThrow();});
 it('rejects unsupported path and unsafe/fractional atomic values',()=>{expect(()=>checkedUtxoEvidence('/api/v1/anything',{},'signet')).toThrow();const value=structuredClone(fixtures['/api/v1/utxo-set/checkpoints']);value.checkpoints[0].totalAmountSats='1.1';expect(()=>checkedUtxoEvidence('/api/v1/utxo-set/checkpoints',value,'signet')).toThrow();});
 it('retains exact aggregate intrablock flows above supply and JS safeinteger limits',()=>{const path='/api/v1/intelligence/utxo/spend-transitions',value=structuredClone(fixtures[path]);Object.assign(value.transitions[0],{created_count:100,spent_count:99,net_utxo_change:1,created_sats:'210000000000000000',spent_sats:'207900000000000000',coin_age_destroyed_sat_seconds:'17962560000000000000000',coin_days_destroyed:2079000000});expect(checkedUtxoEvidence(path,value,'signet').value).toBe(value);value.transitions[0].created_count=300000;expect(()=>checkedUtxoEvidence(path,value,'signet')).toThrow();});
 it('rejects empty or missing modeled fee-rate scenarios rather than fabricate completeness',()=>{const path='/api/v1/intelligence/utxo/economic-thresholds',value=structuredClone(fixtures[path]);value.thresholds.pop();value.count=5;expect(()=>checkedUtxoEvidence(path,value,'signet')).toThrow();expect(()=>checkedUtxoEvidence(path,{thresholds:[],count:0},'signet')).toThrow();});
});
