import { describe, expect, it, vi } from 'vitest';
import { UntypedFormBuilder } from '@angular/forms';
import { BehaviorSubject, of, Subject, throwError } from 'rxjs';
import { PushTransactionComponent } from './push-transaction.component';
import { ApiService } from '@app/services/api.service';
function setup() {
 const network=new BehaviorSubject('signet');const api={postTransaction$:vi.fn(),submitPackage$:vi.fn().mockReturnValue(of({'package_msg':'success','tx-results':{}}))};
 const c=new PushTransactionComponent(new UntypedFormBuilder(),api as any,{network:'signet',networkChanged$:network} as any,{setTitle:vi.fn(),setDescription:vi.fn()} as any,{} as any,{fragment:of(null)} as any,{navigate:vi.fn()} as any,{transform:(x:string)=>x} as any);c.ngOnInit();return {c,api,network};
}
describe('push form lifecycle and exact amount boundary',()=>{
 it('handles failed broadcast retaining input for successful retry',async()=>{const {c,api}=setup();c.pushTxForm.get('txHash').setValue('aa');api.postTransaction$.mockReturnValueOnce(throwError(()=>({error:'controlled unavailable'}))).mockReturnValueOnce(of('txid'));await expect(c.postTx()).resolves.toBeNull();expect(c.error).toContain('controlled unavailable');expect(c.pushTxForm.get('txHash').value).toBe('aa');await expect(c.postTx()).resolves.toBe('txid');expect(c.isLoading).toBe(false);});
 it('guards duplicate broadcasts and cancels on network change and destroy',async()=>{const {c,api,network}=setup();const old=new Subject<string>();api.postTransaction$.mockReturnValue(old);const pending=c.postTx('aa');await expect(c.postTx('aa')).resolves.toBeNull();expect(api.postTransaction$).toHaveBeenCalledOnce();network.next('testnet');expect(old.observed).toBe(false);await expect(pending).resolves.toBeNull();expect(c.txId).toBe('');const fresh=c.postTx('bb');c.ngOnDestroy();await expect(fresh).resolves.toBeNull();await expect(c.postTx('cc')).resolves.toBeNull();expect(api.postTransaction$).toHaveBeenCalledTimes(2);});
 it('refuses fractional burn, excessive precision and nonfinite amounts without dispatch',()=>{for(const [field,value]of[['maxburnamount','1.5'],['maxburnamount','9007199254740993'],['maxfeerate','0.0001'],['maxfeerate','Infinity'],['maxfeerate','1e3']]){const {c,api}=setup();c.submitTxsForm.patchValue({txs:'aa,bb',[field]:value});c.submitTxs();expect(api.submitPackage$).not.toHaveBeenCalled();expect(c.errorPackage).toBeTruthy();}});
 it('converts exact atomic units, preserves zero, guards pending package and cancels destroy',()=>{const {c,api}=setup();const request=new Subject();api.submitPackage$.mockReturnValue(request);c.submitTxsForm.patchValue({txs:'aa,bb',maxfeerate:'1.001',maxburnamount:'1'});c.submitTxs();expect(api.submitPackage$).toHaveBeenCalledWith(['aa','bb'],0.00001001,0.00000001);c.submitTxs();expect(api.submitPackage$).toHaveBeenCalledOnce();c.ngOnDestroy();expect(request.observed).toBe(false);const other=setup();other.c.submitTxsForm.patchValue({txs:'aa,bb',maxfeerate:'0',maxburnamount:'0'});other.c.submitTxs();expect(other.api.submitPackage$).toHaveBeenCalledWith(['aa','bb'],0,0);});
 it('keeps explicit zero constraints on a single-item package',()=>{const {c,api}=setup();c.submitTxsForm.patchValue({txs:'aa',maxfeerate:0,maxburnamount:0});c.submitTxs();expect(api.postTransaction$).not.toHaveBeenCalled();expect(api.submitPackage$).toHaveBeenCalledWith(['aa'],0,0);});
 it('cancels a pending package at network change and retains failed input for retry',()=>{const {c,api,network}=setup();const old=new Subject();api.submitPackage$.mockReturnValueOnce(old).mockReturnValueOnce(throwError(()=>({message:'package unavailable'})));c.submitTxsForm.patchValue({txs:'aa,bb'});c.submitTxs();network.next('testnet');expect(old.observed).toBe(false);expect(c.isLoadingPackage).toBe(false);c.submitTxs();expect(c.errorPackage).toBe('package unavailable');expect(c.submitTxsForm.get('txs').value).toBe('aa,bb');});
 it('serializes zero and one sat without exponent notation',()=>{const api=Object.create(ApiService.prototype);api.apiBaseUrl='';api.apiBasePath='/signet';api.httpClient={post:vi.fn().mockReturnValue(of({}))};api.submitPackage$(['aa'],0,0.00000001);expect(api.httpClient.post).toHaveBeenCalledWith('/signet/api/v1/txs/package?maxfeerate=0.00000000&maxburnamount=0.00000001',['aa']);});
});
