name: 'Print images digest'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: false
        default: 'latest'
        type: string 
jobs:
  route:
    uses: ./.github/workflows/route.yml
    secrets: inherit
    with:
      plan: '{"print_images_sha":"light"}'
      config_ref: 1dd19289af21f4f6be01f874390a180b3af8bb38

  print-images-sha:
    needs: route
    runs-on: ${{ fromJSON(needs.route.outputs.targets).print_images_sha }}
    name: Print digest for images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: digest

      - name: Run script
        working-directory: digest
        run: |
          sh ./docker/scripts/get_image_digest.sh $VERSION
        env: 
          VERSION: ${{ github.event.inputs.version }}
