name: 'Check if servers are in sync'

on: [workflow_dispatch]

jobs:
  route:
    uses: bitcoinuniverseio/.github-private/.github/workflows/route.yml@develop
    secrets: inherit
    with:
      plan: '{"print_backend_sha":"light"}'

  print-backend-sha:
    needs: route
    runs-on: ${{ fromJSON(needs.route.outputs.targets).print_backend_sha }}
    name: Get block height
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Run script
        working-directory: repo
        run: |
          chmod +x ./scripts/get_block_tip_height.sh
          sh ./scripts/get_block_tip_height.sh
