name: 'Print backend hashes'

on: [workflow_dispatch]

jobs:
  route:
    uses: bitcoinuniverseio/.github-private/.github/workflows/route.yml@develop
    secrets: inherit
    with:
      plan: '{"print_backend_sha":"light"}'

  print-backend-sha:
    needs: route
    runs-on: ${{ fromJSON(needs.route.outputs.targets).print_backend_sha }}
    name: Print backend hashes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Run script
        working-directory: repo
        run: |
          chmod +x ./scripts/get_backend_hash.sh
          sh ./scripts/get_backend_hash.sh
